# Import Library

In [ ]:
!pip install datasets pandas -q
!pip install transformers -q
!pip install evaluate -q
!pip install rouge_score -q

  Preparing metadata (setup.py) ... done
  Building wheel for rouge_score (setup.py) ... done

In [ ]:
import pandas as pd
from datasets import Dataset
import numpy as np
import gc
import re
import torch
import evaluate
import itertools
import time

from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM,
    MBartTokenizer, MBartForConditionalGeneration,
    Seq2SeqTrainer, Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq, EarlyStoppingCallback
)
from huggingface_hub import login

## Login Hugging Face

In [ ]:
HF_TOKEN="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"

login(token=HF_TOKEN, add_to_git_credential=False)
print("Logged in to HuggingFace")

Logged in to HuggingFace

# Load Data

In [ ]:
!gdown "https://drive.google.com/uc?id=144fe6vACbTGW3d7wd6f-_CGFo1KtTu-r" -O dataset.csv

file_path = "dataset.csv"

Downloading...
From: https://drive.google.com/uc?id=144fe6vACbTGW3d7wd6f-_CGFo1KtTu-r
To: /content/dataset.csv
100% 14.2M/14.2M [00:00<00:00, 62.7MB/s]

In [ ]:
print("\nSedang membaca data dari Drive...")
df = pd.read_csv(file_path)

print(f"Berhasil memuat {len(df)} baris data!")
display(df.head(2))

df = df.dropna(subset=['title', 'content', 'reference_summary'])
df['input_text'] = "Judul: " + df['title'] + " | Isi: " + df['content']

df_bersih = df[['input_text', 'reference_summary']]
df_bersih.columns = ['text', 'summary']

hf_dataset = Dataset.from_pandas(df_bersih)
if '__index_level_0__' in hf_dataset.column_names:
    hf_dataset = hf_dataset.remove_columns('__index_level_0__')

print("\n=== Selesai! Data Siap Masuk Tahap Tokenisasi ===")
print(hf_dataset)

Sedang membaca data dari Drive...
Berhasil memuat 2297 baris data!

,title,content,reference_summary
0,sejarah peristiwa mei 1998 titik nol reformasi...,julian sihombing seorang mahasiswa tergeletak ...,Peristiwa Mei 1998 merupakan titik nol Reforma...
1,"pariwisata pulau dewata relasi budaya, sejarah...","cokorda yudistira suasana di desa penglipuran,...","Pariwisata Pulau Dewata, Bali, menghadapi tant..."

=== Selesai! Data Siap Masuk Tahap Tokenisasi ===
Dataset({
    features: ['text', 'summary'],
    num_rows: 2147
})

# Pre-Processing

karena ini untuk task text generation and summarization jadi utk text preprocessing tidak mencakup lowercase, menghapus tanda baca (punctuation), dan membuang kata penghubung (stopword).

instead, dilakukan **pembuangan sampah kode HTML, karakter aneh, dan Whitespace Normalization**

In [ ]:
def clean_text_for_transformer(text):
    if not isinstance(text, str):
        return ""

    text = re.sub(r'<[^>]+>', ' ', text)

    text = text.replace('\xa0', ' ').replace('\t', ' ')
    text = re.sub(r'[\r\n]+', ' ', text)

    text = re.sub(r'http\S+|www\.\S+', '', text)

    text = re.sub(r'\s+', ' ', text)

    text = text.strip()

    return text

In [ ]:
def preprocess_dataset_function(batch):
    batch['text'] = [clean_text_for_transformer(t) for t in batch['text']]
    batch['summary'] = [clean_text_for_transformer(s) for s in batch['summary']]
    return batch

In [ ]:
dataset_bersih = hf_dataset.map(preprocess_dataset_function, batched=True)

print("=== Hasil Preprocessing ===")
print(f"Teks Input Sebelum: {hf_dataset[0]['text'][:150]}...")
print(f"Teks Input Sesudah: {dataset_bersih[0]['text'][:150]}...")

Map:   0%|          | 0/2147 [00:00<?, ? examples/s]

=== Hasil Preprocessing ===
Teks Input Sebelum: Judul: sejarah peristiwa mei 1998 titik nol reformasi indonesia | Isi: julian sihombing seorang mahasiswa tergeletak di tepi jalan saat terjadi kerusu...
Teks Input Sesudah: Judul: sejarah peristiwa mei 1998 titik nol reformasi indonesia | Isi: julian sihombing seorang mahasiswa tergeletak di tepi jalan saat terjadi kerusu...

## Chunking System

In [ ]:
def create_chunks(text, chunk_size=400, overlap=0):
    """
    - Jika overlap = 0, ini menjadi Fixed Chunking.
    - Jika overlap > 0, ini menjadi Sliding Window Chunking.
    """
    words = text.split()
    chunks = []

    if len(words) == 0:
        return chunks

    step = chunk_size - overlap
    if step <= 0:
        step = chunk_size

    for i in range(0, len(words), step):
        chunk = words[i : i + chunk_size]
        chunks.append(" ".join(chunk))

        if i + chunk_size >= len(words):
            break

    return chunks

In [ ]:
TARGET_CHUNK_SIZE = 400
OVERLAP_SIZE = 50

all_fixed_chunks = []
all_sliding_chunks = []

print("Memproses chunking pada dataset...")
for text in dataset_bersih['text']:
    fixed = create_chunks(text, chunk_size=TARGET_CHUNK_SIZE, overlap=0)
    all_fixed_chunks.extend(fixed)

    sliding = create_chunks(text, chunk_size=TARGET_CHUNK_SIZE, overlap=OVERLAP_SIZE)
    all_sliding_chunks.extend(sliding)

print()
print("Proses chunking selesai")
print(f"Jumlah Chunk Fixed     : {len(all_fixed_chunks)}")
print(f"Jumlah Chunk Sliding   : {len(all_sliding_chunks)}")

Memproses chunking pada dataset...

Proses chunking selesai
Jumlah Chunk Fixed     : 4855
Jumlah Chunk Sliding   : 5149

Karena artikel edukasi sangat bergantung pada urutan penjelasan sebab-akibat. Fixed chunking berisiko memotong persis di tengah logika tersebut (misal, terpotong sebelum bagian kesimpulan kalimat) maka dari itu kami memilih Sliding window (dengan overlap sekitar 50 kata) untuk memastikan "jembatan logika" itu tetap utuh terbaca oleh model.

## Chunking Analysis

In [ ]:
def analyze_chunks(chunk_list, name):
    total_chunks = len(chunk_list)
    lengths = [len(c.split()) for c in chunk_list]
    avg_length = np.mean(lengths) if total_chunks > 0 else 0
    max_length = np.max(lengths) if total_chunks > 0 else 0
    min_length = np.min(lengths) if total_chunks > 0 else 0

    print(f"=== Analisis {name} ===")
    print(f"Total Chunks Dihasilkan : {total_chunks}")
    print(f"Rata-rata Panjang Chunk : {avg_length:.2f} kata")
    print(f"Chunk Terpanjang        : {max_length} kata")
    print(f"Chunk Terpendek         : {min_length} kata\n")

In [ ]:
analyze_chunks(all_fixed_chunks, "Fixed Chunking (Overlap 0)")
analyze_chunks(all_sliding_chunks, f"Sliding Window (Overlap {OVERLAP_SIZE})")

print("=== Observasi Perilaku Overlap pada Teks Pertama ===")
sample_text = dataset_bersih['text'][0]
sample_sliding = create_chunks(sample_text, chunk_size=TARGET_CHUNK_SIZE, overlap=OVERLAP_SIZE)

if len(sample_sliding) > 1:
    akhir_chunk_1 = " ".join(sample_sliding[0].split()[-10:])
    awal_chunk_2 = " ".join(sample_sliding[1].split()[:10])

    print("10 Kata TERAKHIR di Chunk 1:")
    print(f"...{akhir_chunk_1}")
    print("\n10 Kata PERTAMA di Chunk 2:")
    print(f"{awal_chunk_2}...")
else:
    print("Teks pertama terlalu pendek untuk dibagi menjadi beberapa chunk.")

=== Analisis Fixed Chunking (Overlap 0) ===
Total Chunks Dihasilkan : 4855
Rata-rata Panjang Chunk : 314.18 kata
Chunk Terpanjang        : 400 kata
Chunk Terpendek         : 1 kata

=== Analisis Sliding Window (Overlap 50) ===
Total Chunks Dihasilkan : 5149
Rata-rata Panjang Chunk : 325.39 kata
Chunk Terpanjang        : 400 kata
Chunk Terpendek         : 18 kata

=== Observasi Perilaku Overlap pada Teks Pertama ===
10 Kata TERAKHIR di Chunk 1:
...pada akhir tahun 1996, utang luar negeri pemerintah indonesia mencapai

10 Kata PERTAMA di Chunk 2:
di thailand sekitar bulan mei 1997, pemerintah sangat yakin bahwa...

**Sliding Window** adalah pilihan yang paling tangguh (robust) untuk dataset artikel edukasi sejarah ini

## Fixed Chunk

In [ ]:
try:
    del all_fixed_chunks
    del fixed
    print("Variabel Fixed Chunking berhasil dihapus dari memori.")
except NameError:
    pass

gc.collect()

Variabel Fixed Chunking berhasil dihapus dari memori.

72

## Bind Hasil Chunk dengan Data Asli

In [ ]:
TARGET_CHUNK_SIZE = 400
OVERLAP_SIZE = 50
data_final = []

print("\nSedang merakit ulang dataset Sliding Window...")

for i in range(len(dataset_bersih)):
    teks_asli = dataset_bersih['text'][i]
    ringkasan_asli = dataset_bersih['summary'][i]

    chunks = create_chunks(teks_asli, chunk_size=TARGET_CHUNK_SIZE, overlap=OVERLAP_SIZE)

    for chunk in chunks:
        data_final.append({
            'text': chunk,
            'summary': ringkasan_asli
        })

print()
print("Perakitan Sliding Window selesai")
print(f"Jumlah Chunk yang Diperoleh : {len(data_final)}")

Sedang merakit ulang dataset Sliding Window...

Perakitan Sliding Window selesai
Jumlah Chunk yang Diperoleh : 5149

### Format Hugging Face

In [ ]:
df_final = pd.DataFrame(data_final)

dataset_siap_train = Dataset.from_pandas(df_final)

print("\nDATASET FINAL HUGGING FACE BERHASIL DIBUAT")
print(dataset_siap_train)
print(f"\nPreview Input (Chunk) : {dataset_siap_train[0]['text'][:150]}...")
print(f"Preview Target        : {dataset_siap_train[0]['summary'][:150]}...")

DATASET FINAL HUGGING FACE BERHASIL DIBUAT
Dataset({
    features: ['text', 'summary'],
    num_rows: 5149
})

Preview Input (Chunk) : Judul: sejarah peristiwa mei 1998 titik nol reformasi indonesia | Isi: julian sihombing seorang mahasiswa tergeletak di tepi jalan saat terjadi kerusu...
Preview Target        : Peristiwa Mei 1998 merupakan titik nol Reformasi di Indonesia, yang ditandai oleh kerusuhan dan demonstrasi massal pada tanggal 12 Mei 1998. Krisis ek...

## Data Split

In [ ]:
dataset_split = dataset_siap_train.train_test_split(
    test_size=0.3,
    seed=42
)

temp_split = dataset_split['test'].train_test_split(
    test_size=0.5,
    seed=42
)

dataset_split['validation'] = temp_split['train']
dataset_split['test'] = temp_split['test']

print("=== HASIL PEMBAGIAN DATASET ===")
print(dataset_split)

print(f"\nJumlah Data Latih (Training)   : {len(dataset_split['train'])} baris")
print(f"Jumlah Data Validasi           : {len(dataset_split['validation'])} baris")
print(f"Jumlah Data Uji (Test)         : {len(dataset_split['test'])} baris")

=== HASIL PEMBAGIAN DATASET ===
DatasetDict({
    train: Dataset({
        features: ['text', 'summary'],
        num_rows: 3604
    })
    test: Dataset({
        features: ['text', 'summary'],
        num_rows: 773
    })
    validation: Dataset({
        features: ['text', 'summary'],
        num_rows: 772
    })
})

Jumlah Data Latih (Training)   : 3604 baris
Jumlah Data Validasi           : 772 baris
Jumlah Data Uji (Test)         : 773 baris

## Tokenizing

### Flan-T5 Tokenizing

In [ ]:
FLAN_MODEL = "google/flan-t5-base"

print(f"Sedang memuat Tokenizer untuk model: {FLAN_MODEL}...")
tokenizer_flan = AutoTokenizer.from_pretrained(FLAN_MODEL)

MAX_INPUT_LENGTH = 400
MAX_TARGET_LENGTH = 100

def preprocess_function(examples):
    model_inputs = tokenizer_flan(
        examples["text"],
        max_length=MAX_INPUT_LENGTH,
        truncation=True  # hapus padding di sini
    )
    labels = tokenizer_flan(
        text_target=examples["summary"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True  # hapus padding di sini
    )
    # Ganti pad_token_id dengan -100 agar tidak dihitung dalam loss
    model_inputs["labels"] = [
        [(token if token != tokenizer_flan.pad_token_id else -100) for token in label]
        for label in labels["input_ids"]
    ]
    return model_inputs

print("Sedang menerjemahkan teks menjadi Tensor (Angka)...")
tokenized_flan = dataset_split.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset_split["train"].column_names
)

print("\n=== TOKENISASI SELESAI ===")
print("Struktur Data yang akan masuk ke Model:")
print(tokenized_flan)

# Verifikasi label tidak semua -100
sample = tokenized_flan["train"][0]
valid_labels = [l for l in sample["labels"] if l != -100]
print(f"\nSample label (non-padding): {valid_labels[:10]}")
print(f"Jumlah token valid: {len(valid_labels)}")

Sedang memuat Tokenizer untuk model: google/flan-t5-base...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

Sedang menerjemahkan teks menjadi Tensor (Angka)...

Map:   0%|          | 0/3604 [00:00<?, ? examples/s]

Map:   0%|          | 0/773 [00:00<?, ? examples/s]

Map:   0%|          | 0/772 [00:00<?, ? examples/s]

=== TOKENISASI SELESAI ===
Struktur Data yang akan masuk ke Model:
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 3604
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 773
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 772
    })
})

Sample label (non-padding): [4892, 23, 6214, 29, 2738, 20930, 32, 140, 5952, 2168]
Jumlah token valid: 100

### IndoBART Tokenizing

In [ ]:
BART_MODEL = "indobenchmark/indobart-v2"
print(f"Sedang memuat Tokenizer untuk model: {BART_MODEL}...")

if "indobart" in BART_MODEL.lower():
    tokenizer_bart = MBartTokenizer.from_pretrained(BART_MODEL)
    tokenizer_bart.src_lang = "id_ID"
    tokenizer_bart.tgt_lang = "id_ID"
else:
    tokenizer_bart = AutoTokenizer.from_pretrained(BART_MODEL)

MAX_INPUT_LENGTH = 400
MAX_TARGET_LENGTH = 100

def preprocess_function(examples):
    model_inputs = tokenizer_bart(
        examples["text"],
        max_length=MAX_INPUT_LENGTH,
        padding="max_length",
        truncation=True
    )

    labels = tokenizer_bart(
        text_target=examples["summary"],
        max_length=MAX_TARGET_LENGTH,
        padding="max_length",
        truncation=True
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

print("Sedang menerjemahkan teks menjadi Tensor (Angka)...")

tokenized_bart = dataset_split.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset_split["train"].column_names
)

print("\n=== TOKENISASI SELESAI ===")
print("Struktur Data yang akan masuk ke Model:")
print(tokenized_bart)

Sedang memuat Tokenizer untuk model: indobenchmark/indobart-v2...

tokenizer_config.json:   0%|          | 0.00/303 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/932k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

Sedang menerjemahkan teks menjadi Tensor (Angka)...

Map:   0%|          | 0/3604 [00:00<?, ? examples/s]

Map:   0%|          | 0/773 [00:00<?, ? examples/s]

Map:   0%|          | 0/772 [00:00<?, ? examples/s]

=== TOKENISASI SELESAI ===
Struktur Data yang akan masuk ke Model:
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 3604
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 773
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 772
    })
})

# Training and Implementation

In [ ]:
print(f"Memuat model FLAN-T5: {FLAN_MODEL}...")
model_flan = AutoModelForSeq2SeqLM.from_pretrained(FLAN_MODEL)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_flan = model_flan.to(device)

total_params = sum(p.numel() for p in model_flan.parameters())
trainable_params = sum(p.numel() for p in model_flan.parameters() if p.requires_grad)

print(f"\n=== Info Model FLAN-T5 ===")
print(f"Device    : {device}")
print(f"Total Params    : {total_params:,}")
print(f"Trainable Params: {trainable_params:,}")
print("Model FLAN-T5 siap digunakan!")

Memuat model FLAN-T5: google/flan-t5-base...

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

=== Info Model FLAN-T5 ===
Device    : cuda
Total Params    : 247,577,856
Trainable Params: 247,577,856
Model FLAN-T5 siap digunakan!

In [ ]:
print(f"Memuat model IndoBART: {BART_MODEL}...")
model_bart = MBartForConditionalGeneration.from_pretrained(BART_MODEL)
model_bart = model_bart.to(device)

total_params_bart = sum(p.numel() for p in model_bart.parameters())
trainable_params_bart = sum(p.numel() for p in model_bart.parameters() if p.requires_grad)

print(f"\n=== Info Model IndoBART ===")
print(f"Device          : {device}")
print(f"Total Params    : {total_params_bart:,}")
print(f"Trainable Params: {trainable_params_bart:,}")
print("Model IndoBART siap digunakan!")

Memuat model IndoBART: indobenchmark/indobart-v2...

config.json:   0%|          | 0.00/1.71k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/526M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/267 [00:00<?, ?it/s]

=== Info Model IndoBART ===
Device          : cuda
Total Params    : 131,543,040
Trainable Params: 131,543,040
Model IndoBART siap digunakan!

## FLAN-T5

### Metrik Evaluasi

In [ ]:
rouge = evaluate.load("rouge")

def compute_metrics_flan(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer_flan.batch_decode(predictions, skip_special_tokens=True)
    labels = [[(l if l != -100 else tokenizer_flan.pad_token_id) for l in label] for label in labels]
    decoded_labels = tokenizer_flan.batch_decode(labels, skip_special_tokens=True)
    decoded_preds  = ["\n".join(p.strip().split(".")) for p in decoded_preds]
    decoded_labels = ["\n".join(l.strip().split(".")) for l in decoded_labels]
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {k: round(v, 4) for k, v in result.items()}

data_collator_flan = DataCollatorForSeq2Seq(
    tokenizer=tokenizer_flan,
    model=model_flan,
    padding=True,
    label_pad_token_id=-100
)

model.safetensors:   0%|          | 0.00/526M [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

### Fine-Tune

In [ ]:
training_args_flan = Seq2SeqTrainingArguments(
    output_dir="./flan_t5_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    predict_with_generate=True,
    generation_max_length=100,
    load_best_model_at_end=True,
    metric_for_best_model="rouge2",
    fp16=torch.cuda.is_available(),
    logging_dir="./logs_flan",
    logging_steps=50,
    report_to="none",
)

trainer_flan = Seq2SeqTrainer(
    model=model_flan,
    args=training_args_flan,
    train_dataset=tokenized_flan["train"],
    eval_dataset=tokenized_flan["validation"],
    processing_class=tokenizer_flan,
    data_collator=data_collator_flan,
    compute_metrics=compute_metrics_flan,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("=== Memulai Fine-Tuning FLAN-T5 ===")
trainer_flan.train()
print("\nFine-Tuning FLAN-T5 selesai!")

# Simpan model
trainer_flan.save_model("./flan_t5_finetuned")
tokenizer_flan.save_pretrained("./flan_t5_finetuned")
print("Model FLAN-T5 disimpan ke ./flan_t5_finetuned")

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

=== Memulai Fine-Tuning FLAN-T5 ===

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

##

## IndoBART

### Metrik Evaluasi

In [ ]:
def compute_metrics_bart(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer_bart.batch_decode(predictions, skip_special_tokens=True)
    labels = [[(l if l != -100 else tokenizer_bart.pad_token_id) for l in label] for label in labels]
    decoded_labels = tokenizer_bart.batch_decode(labels, skip_special_tokens=True)
    decoded_preds  = ["\n".join(p.strip().split(".")) for p in decoded_preds]
    decoded_labels = ["\n".join(l.strip().split(".")) for l in decoded_labels]
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {k: round(v, 4) for k, v in result.items()}

data_collator_bart = DataCollatorForSeq2Seq(
    tokenizer=tokenizer_bart,
    model=model_bart,
    padding=True,
    label_pad_token_id=-100
)

### Fine-Tune

In [ ]:
training_args_bart = Seq2SeqTrainingArguments(
    output_dir="./indobart_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=3e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    predict_with_generate=True,
    generation_max_length=100,
    load_best_model_at_end=True,
    metric_for_best_model="rouge2",
    fp16=torch.cuda.is_available(),
    logging_dir="./logs_bart",
    logging_steps=50,
    report_to="none",
)

trainer_bart = Seq2SeqTrainer(
    model=model_bart,
    args=training_args_bart,
    train_dataset=tokenized_bart["train"],
    eval_dataset=tokenized_bart["validation"],
    processing_class=tokenizer_bart,
    data_collator=data_collator_bart,
    compute_metrics=compute_metrics_bart,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("=== Memulai Fine-Tuning IndoBART ===")
trainer_bart.train()
print("\nFine-Tuning IndoBART selesai!")

trainer_bart.save_model("./indobart_finetuned")
tokenizer_bart.save_pretrained("./indobart_finetuned")
print("Model IndoBART disimpan ke ./indobart_finetuned")

## Summarization Pipeline

### FLAN-T5

In [ ]:
def summarize_with_flan(text, max_length=128, min_length=30, num_beams=4):
    """
    Ringkas teks menggunakan FLAN-T5 fine-tuned.
    Args:
        text       : teks input (str)
        max_length : panjang maksimum ringkasan (token)
        min_length : panjang minimum ringkasan (token)
        num_beams  : lebar beam search
    Returns:
        summary    : ringkasan (str)
    """
    inputs = tokenizer_flan(
        text,
        return_tensors="pt",
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding=True
    ).to(device)

    outputs = model_flan.generate(
        **inputs,
        max_length=max_length,
        min_length=min_length,
        num_beams=num_beams,
        early_stopping=True,
        no_repeat_ngram_size=3,
        length_penalty=2.0
    )
    return tokenizer_flan.decode(outputs[0], skip_special_tokens=True)

### IndoBART

In [ ]:
def summarize_with_bart(text, max_length=128, min_length=30, num_beams=4):
    """
    Ringkas teks menggunakan IndoBART fine-tuned.
    """
    inputs = tokenizer_bart(
        text,
        return_tensors="pt",
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding=True
    ).to(device)

    forced_bos = tokenizer_bart.lang_code_to_id.get("id_ID")

    outputs = model_bart.generate(
        **inputs,
        max_length=max_length,
        min_length=min_length,
        num_beams=num_beams,
        early_stopping=True,
        no_repeat_ngram_size=3,
        length_penalty=2.0,
        forced_bos_token_id=forced_bos
    )
    return tokenizer_bart.decode(outputs[0], skip_special_tokens=True)

### Full-Pipeline

In [ ]:
def full_summarization_pipeline(text, model_choice="flan",
                                 chunk_size=400, overlap=50,
                                 max_length=128, min_length=30, num_beams=4):
    """
    Pipeline lengkap: Chunk → Model → Summary

    1. Potong teks menjadi chunk dengan sliding window.
    2. Ringkas tiap chunk secara independen.
    3. Gabungkan semua ringkasan chunk menjadi satu teks.
    4. Jika gabungan masih terlalu panjang, ringkas sekali lagi (reduce step).

    Args:
        text        : teks panjang (str)
        model_choice: "flan" atau "bart"
        chunk_size  : ukuran chunk (kata)
        overlap     : jumlah kata overlap antar chunk
        max_length  : max token output per chunk
        min_length  : min token output per chunk
        num_beams   : lebar beam search
    Returns:
        final_summary: ringkasan akhir (str)
        chunk_summaries: list ringkasan per chunk
    """
    summarize_fn = summarize_with_flan if model_choice == "flan" else summarize_with_bart

    # Step 1 – Chunking
    chunks = create_chunks(text, chunk_size=chunk_size, overlap=overlap)
    print(f"  → Teks dipecah menjadi {len(chunks)} chunk")

    # Step 2 – Summarize per chunk
    chunk_summaries = []
    for idx, chunk in enumerate(chunks):
        summary = summarize_fn(chunk, max_length=max_length,
                               min_length=min_length, num_beams=num_beams)
        chunk_summaries.append(summary)
        print(f"  → Chunk {idx+1}/{len(chunks)} diringkas")

    # Step 3 – Gabungkan
    combined = " ".join(chunk_summaries)

    # Step 4 – Reduce (jika gabungan masih panjang)
    combined_words = combined.split()
    if len(combined_words) > chunk_size:
        print(f"  → Gabungan terlalu panjang ({len(combined_words)} kata), melakukan reduce...")
        final_summary = summarize_fn(combined, max_length=max_length,
                                     min_length=min_length, num_beams=num_beams)
    else:
        final_summary = combined

    return final_summary, chunk_summaries

## Hyperparameter Testing

In [ ]:
# ── Definisi grid hyperparameter ─────────────────────────────────────
HYPERPARAM_GRID = {
    "max_length": [64, 128, 200],
    "min_length": [20, 40],
    "num_beams" : [2, 4, 6]
}

# Ambil 5 sampel test
N_SAMPLES = 5
test_samples = dataset_split["test"].select(range(N_SAMPLES))

comparison_results = []

print("=== Mulai Hyperparameter Testing ===")
print(f"Grid: {HYPERPARAM_GRID}")
print(f"Sampel  : {N_SAMPLES} artikel dari test set")
print(f"Model   : FLAN-T5 & IndoBART")
print("-" * 70)

for max_len, min_len, beams in itertools.product(
    HYPERPARAM_GRID["max_length"],
    HYPERPARAM_GRID["min_length"],
    HYPERPARAM_GRID["num_beams"]
):
    # Lewati kombinasi tidak valid
    if min_len >= max_len:
        continue

    for model_choice in ["flan", "bart"]:
        flan_scores, bart_scores_r = [], []
        latencies = []

        for sample in test_samples:
            t_start = time.time()
            pred, _ = full_summarization_pipeline(
                sample["text"],
                model_choice=model_choice,
                max_length=max_len,
                min_length=min_len,
                num_beams=beams
            )
            latencies.append(time.time() - t_start)

            score = rouge.compute(
                predictions=[pred],
                references=[sample["summary"]],
                use_stemmer=True
            )
            flan_scores.append(score["rouge2"])

        avg_r2  = round(sum(flan_scores) / len(flan_scores), 4)
        avg_lat = round(sum(latencies) / len(latencies), 2)

        comparison_results.append({
            "model"      : model_choice.upper(),
            "max_length" : max_len,
            "min_length" : min_len,
            "num_beams"  : beams,
            "rouge2_avg" : avg_r2,
            "latency_s"  : avg_lat
        })

        print(f"[{model_choice.upper():8s}] max={max_len:3d} min={min_len:2d} beams={beams} | ROUGE-2={avg_r2:.4f} | latency={avg_lat:.2f}s")

df_hyperparam = pd.DataFrame(comparison_results)
print("\n=== Tabel Perbandingan Hyperparameter ===")
display(df_hyperparam.sort_values(["model", "rouge2_avg"], ascending=[True, False]))

## Testing

In [ ]:
# ── Cari konfigurasi terbaik per model ───────────────────────────────
best_flan = df_hyperparam[df_hyperparam["model"] == "FLAN"] \
    .sort_values("rouge2_avg", ascending=False).iloc[0]
best_bart = df_hyperparam[df_hyperparam["model"] == "BART"] \
    .sort_values("rouge2_avg", ascending=False).iloc[0]

print("=== Konfigurasi Terbaik ===")
print(f"FLAN-T5 : max={int(best_flan.max_length)} min={int(best_flan.min_length)} beams={int(best_flan.num_beams)} | ROUGE-2={best_flan.rouge2_avg}")
print(f"IndoBART: max={int(best_bart.max_length)} min={int(best_bart.min_length)} beams={int(best_bart.num_beams)} | ROUGE-2={best_bart.rouge2_avg}")

# ── Generate ringkasan test set ───────────────────────────────────────
results = []
print("\n=== Menghasilkan Ringkasan Test Set ===")

for i, sample in enumerate(dataset_split["test"]):
    flan_summary, _ = full_summarization_pipeline(
        sample["text"], model_choice="flan",
        max_length=int(best_flan.max_length),
        min_length=int(best_flan.min_length),
        num_beams=int(best_flan.num_beams)
    )
    bart_summary, _ = full_summarization_pipeline(
        sample["text"], model_choice="bart",
        max_length=int(best_bart.max_length),
        min_length=int(best_bart.min_length),
        num_beams=int(best_bart.num_beams)
    )
    results.append({
        "id"               : i + 1,
        "input_text"       : sample["text"][:200] + "...",
        "reference_summary": sample["summary"],
        "flan_summary"     : flan_summary,
        "bart_summary"     : bart_summary
    })

    if (i + 1) % 10 == 0:
        print(f"  → {i+1}/{len(dataset_split['test'])} sampel diproses")

df_results = pd.DataFrame(results)
print(f"\nTotal ringkasan dihasilkan: {len(df_results)}")
display(df_results.head(3))

In [ ]:
# ── Simpan ke CSV ─────────────────────────────────────────────────────
CSV_PATH = "generated_summaries.csv"
df_results.to_csv(CSV_PATH, index=False, encoding="utf-8-sig")
print(f"Ringkasan disimpan ke CSV: {CSV_PATH}")

# ── Simpan ke TXT ─────────────────────────────────────────────────────
TXT_PATH = "generated_summaries.txt"
with open(TXT_PATH, "w", encoding="utf-8") as f:
    for _, row in df_results.iterrows():
        f.write(f"{'='*70}\n")
        f.write(f"ID         : {row['id']}\n")
        f.write(f"INPUT      : {row['input_text']}\n")
        f.write(f"REFERENSI  : {row['reference_summary']}\n")
        f.write(f"FLAN-T5    : {row['flan_summary']}\n")
        f.write(f"IndoBART   : {row['bart_summary']}\n")
        f.write("\n")
print(f"Ringkasan disimpan ke TXT : {TXT_PATH}")

## Evaluasi

In [ ]:
# ── Hitung ROUGE lengkap untuk semua hasil ───────────────────────────
rouge_full = evaluate.load("rouge")

flan_preds = df_results["flan_summary"].tolist()
bart_preds = df_results["bart_summary"].tolist()
refs       = df_results["reference_summary"].tolist()

scores_flan = rouge_full.compute(predictions=flan_preds, references=refs, use_stemmer=True)
scores_bart = rouge_full.compute(predictions=bart_preds, references=refs, use_stemmer=True)

avg_len_flan = round(sum(len(s.split()) for s in flan_preds) / len(flan_preds), 1)
avg_len_bart = round(sum(len(s.split()) for s in bart_preds) / len(bart_preds), 1)
avg_len_ref  = round(sum(len(s.split()) for s in refs)       / len(refs),       1)

comparison_table = pd.DataFrame([
    {
        "Model"          : "FLAN-T5 (fine-tuned)",
        "ROUGE-1"        : round(scores_flan["rouge1"],  4),
        "ROUGE-2"        : round(scores_flan["rouge2"],  4),
        "ROUGE-L"        : round(scores_flan["rougeL"],  4),
        "Avg Length (kata)" : avg_len_flan,
        "Best max_length" : int(best_flan.max_length),
        "Best num_beams"  : int(best_flan.num_beams),
    },
    {
        "Model"          : "IndoBART (fine-tuned)",
        "ROUGE-1"        : round(scores_bart["rouge1"],  4),
        "ROUGE-2"        : round(scores_bart["rouge2"],  4),
        "ROUGE-L"        : round(scores_bart["rougeL"],  4),
        "Avg Length (kata)" : avg_len_bart,
        "Best max_length" : int(best_bart.max_length),
        "Best num_beams"  : int(best_bart.num_beams),
    },
    {
        "Model"          : "Reference Summary",
        "ROUGE-1"        : "-",
        "ROUGE-2"        : "-",
        "ROUGE-L"        : "-",
        "Avg Length (kata)" : avg_len_ref,
        "Best max_length" : "-",
        "Best num_beams"  : "-",
    }
])

print("=" * 70)
print("MODEL COMPARISON RAW OUTPUT")
print("=" * 70)
display(comparison_table)

# Simpan tabel ke CSV
comparison_table.to_csv("model_comparison.csv", index=False, encoding="utf-8-sig")
print("\nTabel disimpan ke model_comparison.csv")

# ── Ringkasan Kesimpulan ──────────────────────────────────────────────
winner = "FLAN-T5" if scores_flan["rouge2"] >= scores_bart["rouge2"] else "IndoBART"
print(f"\n>>> Model dengan ROUGE-2 terbaik: {winner}")