# Import Library

In [1]:
!pip install datasets pandas -q
!pip install transformers -q
!pip install evaluate -q
!pip install rouge_score -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for rouge_score (setup.py) ... done

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
from datasets import Dataset
import numpy as np
import gc
import re
import torch
import evaluate
import itertools
import time

from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM,
    MBartTokenizer, MBartForConditionalGeneration,
    Seq2SeqTrainer, Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq, EarlyStoppingCallback
)
from huggingface_hub import login

## Login Hugging Face

In [4]:
HF_TOKEN="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"

login(token=HF_TOKEN, add_to_git_credential=False)
print("Logged in to HuggingFace")

Logged in to HuggingFace

# Load Data

In [5]:
!gdown "https://drive.google.com/uc?id=144fe6vACbTGW3d7wd6f-_CGFo1KtTu-r" -O dataset.csv

file_path = "dataset.csv"

Downloading...
From: https://drive.google.com/uc?id=144fe6vACbTGW3d7wd6f-_CGFo1KtTu-r
To: /content/dataset.csv
100% 14.2M/14.2M [00:00<00:00, 61.1MB/s]

In [6]:
print("\nSedang membaca data dari Drive...")
df = pd.read_csv(file_path)

print(f"Berhasil memuat {len(df)} baris data!")
display(df.head(2))

df = df.dropna(subset=['title', 'content', 'reference_summary'])
df['input_text'] = "Judul: " + df['title'] + " | Isi: " + df['content']

df_bersih = df[['input_text', 'reference_summary']]
df_bersih.columns = ['text', 'summary']

hf_dataset = Dataset.from_pandas(df_bersih)
if '__index_level_0__' in hf_dataset.column_names:
    hf_dataset = hf_dataset.remove_columns('__index_level_0__')

print("\n=== Selesai! Data Siap Masuk Tahap Tokenisasi ===")
print(hf_dataset)

Sedang membaca data dari Drive...
Berhasil memuat 2297 baris data!

,title,content,reference_summary
0,sejarah peristiwa mei 1998 titik nol reformasi...,julian sihombing seorang mahasiswa tergeletak ...,Peristiwa Mei 1998 merupakan titik nol Reforma...
1,"pariwisata pulau dewata relasi budaya, sejarah...","cokorda yudistira suasana di desa penglipuran,...","Pariwisata Pulau Dewata, Bali, menghadapi tant..."

=== Selesai! Data Siap Masuk Tahap Tokenisasi ===
Dataset({
    features: ['text', 'summary'],
    num_rows: 2147
})

# Pre-Processing

karena ini untuk task text generation and summarization jadi utk text preprocessing tidak mencakup lowercase, menghapus tanda baca (punctuation), dan membuang kata penghubung (stopword).

instead, dilakukan **pembuangan sampah kode HTML, karakter aneh, dan Whitespace Normalization**

In [7]:
def clean_text_for_transformer(text):
    if not isinstance(text, str):
        return ""

    text = re.sub(r'<[^>]+>', ' ', text)

    text = text.replace('\xa0', ' ').replace('\t', ' ')
    text = re.sub(r'[\r\n]+', ' ', text)

    text = re.sub(r'http\S+|www\.\S+', '', text)

    text = re.sub(r'\s+', ' ', text)

    text = text.strip()

    return text

In [8]:
def preprocess_dataset_function(batch):
    batch['text'] = [clean_text_for_transformer(t) for t in batch['text']]
    batch['summary'] = [clean_text_for_transformer(s) for s in batch['summary']]
    return batch

In [9]:
dataset_bersih = hf_dataset.map(preprocess_dataset_function, batched=True)

print("=== Hasil Preprocessing ===")
print(f"Teks Input Sebelum: {hf_dataset[0]['text'][:150]}...")
print(f"Teks Input Sesudah: {dataset_bersih[0]['text'][:150]}...")

Map:   0%|          | 0/2147 [00:00<?, ? examples/s]

=== Hasil Preprocessing ===
Teks Input Sebelum: Judul: sejarah peristiwa mei 1998 titik nol reformasi indonesia | Isi: julian sihombing seorang mahasiswa tergeletak di tepi jalan saat terjadi kerusu...
Teks Input Sesudah: Judul: sejarah peristiwa mei 1998 titik nol reformasi indonesia | Isi: julian sihombing seorang mahasiswa tergeletak di tepi jalan saat terjadi kerusu...

In [10]:
dataset_siap_train = dataset_bersih

print("\nDATASET FINAL HUGGING FACE BERHASIL DIBUAT")
print(dataset_siap_train)

DATASET FINAL HUGGING FACE BERHASIL DIBUAT
Dataset({
    features: ['text', 'summary'],
    num_rows: 2147
})

### Format Hugging Face

## Data Split

In [11]:
dataset_split = dataset_siap_train.train_test_split(
    test_size=0.3,
    seed=42
)

temp_split = dataset_split['test'].train_test_split(
    test_size=0.5,
    seed=42
)

dataset_split['validation'] = temp_split['train']
dataset_split['test'] = temp_split['test']

print("=== HASIL PEMBAGIAN DATASET ===")
print(dataset_split)

print(f"\nJumlah Data Latih (Training)   : {len(dataset_split['train'])} baris")
print(f"Jumlah Data Validasi           : {len(dataset_split['validation'])} baris")
print(f"Jumlah Data Uji (Test)         : {len(dataset_split['test'])} baris")

=== HASIL PEMBAGIAN DATASET ===
DatasetDict({
    train: Dataset({
        features: ['text', 'summary'],
        num_rows: 1502
    })
    test: Dataset({
        features: ['text', 'summary'],
        num_rows: 323
    })
    validation: Dataset({
        features: ['text', 'summary'],
        num_rows: 322
    })
})

Jumlah Data Latih (Training)   : 1502 baris
Jumlah Data Validasi           : 322 baris
Jumlah Data Uji (Test)         : 323 baris

## Tokenizing

### Flan-T5 Tokenizing

In [12]:
FLAN_MODEL = "google/flan-t5-base"

print(f"Sedang memuat Tokenizer untuk model: {FLAN_MODEL}...")
tokenizer_flan = AutoTokenizer.from_pretrained(FLAN_MODEL)

MAX_INPUT_LENGTH = 1024
MAX_TARGET_LENGTH = 150

def preprocess_function(examples):
    model_inputs = tokenizer_flan(
        examples["text"],
        max_length=MAX_INPUT_LENGTH,
        truncation=True  # hapus padding di sini
    )
    labels = tokenizer_flan(
        text_target=examples["summary"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True  # hapus padding di sini
    )
    # Ganti pad_token_id dengan -100 agar tidak dihitung dalam loss
    model_inputs["labels"] = [
        [(token if token != tokenizer_flan.pad_token_id else -100) for token in label]
        for label in labels["input_ids"]
    ]
    return model_inputs

print("Sedang menerjemahkan teks menjadi Tensor (Angka)...")
tokenized_flan = dataset_split.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset_split["train"].column_names
)

print("\n=== TOKENISASI SELESAI ===")
print("Struktur Data yang akan masuk ke Model:")
print(tokenized_flan)

# Verifikasi label tidak semua -100
sample = tokenized_flan["train"][0]
valid_labels = [l for l in sample["labels"] if l != -100]
print(f"\nSample label (non-padding): {valid_labels[:10]}")
print(f"Jumlah token valid: {len(valid_labels)}")

Sedang memuat Tokenizer untuk model: google/flan-t5-base...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

Sedang menerjemahkan teks menjadi Tensor (Angka)...

Map:   0%|          | 0/1502 [00:00<?, ? examples/s]

Map:   0%|          | 0/323 [00:00<?, ? examples/s]

Map:   0%|          | 0/322 [00:00<?, ? examples/s]

=== TOKENISASI SELESAI ===
Struktur Data yang akan masuk ke Model:
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1502
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 323
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 322
    })
})

Sample label (non-padding): [4511, 1259, 26, 1598, 146, 29, 23, 9, 1076, 4010]
Jumlah token valid: 150

### IndoBART Tokenizing

In [13]:
BART_MODEL = "indobenchmark/indobart-v2"
print(f"Sedang memuat Tokenizer untuk model: {BART_MODEL}...")

if "indobart" in BART_MODEL.lower():
    tokenizer_bart = MBartTokenizer.from_pretrained(BART_MODEL)
    tokenizer_bart.src_lang = "id_ID"
    tokenizer_bart.tgt_lang = "id_ID"
else:
    tokenizer_bart = AutoTokenizer.from_pretrained(BART_MODEL)

MAX_INPUT_LENGTH = 1024
MAX_TARGET_LENGTH = 150

def preprocess_function(examples):
    model_inputs = tokenizer_bart(
        examples["text"],
        max_length=MAX_INPUT_LENGTH,
        truncation=True
    )

    labels = tokenizer_bart(
        text_target=examples["summary"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True
    )

    # Ganti pad_token_id dengan -100 agar tidak dihitung dalam loss
    model_inputs["labels"] = [
        [(token if token != tokenizer_bart.pad_token_id else -100) for token in label]
        for label in labels["input_ids"]
    ]
    return model_inputs

print("Sedang menerjemahkan teks menjadi Tensor (Angka)...")

tokenized_bart = dataset_split.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset_split["train"].column_names
)

print("\n=== TOKENISASI SELESAI ===")
print("Struktur Data yang akan masuk ke Model:")
print(tokenized_bart)

Sedang memuat Tokenizer untuk model: indobenchmark/indobart-v2...

tokenizer_config.json:   0%|          | 0.00/303 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/932k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

Sedang menerjemahkan teks menjadi Tensor (Angka)...

Map:   0%|          | 0/1502 [00:00<?, ? examples/s]

Map:   0%|          | 0/323 [00:00<?, ? examples/s]

Map:   0%|          | 0/322 [00:00<?, ? examples/s]

=== TOKENISASI SELESAI ===
Struktur Data yang akan masuk ke Model:
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1502
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 323
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 322
    })
})

# Training and Implementation

In [14]:
print(f"Memuat model FLAN-T5: {FLAN_MODEL}...")
model_flan = AutoModelForSeq2SeqLM.from_pretrained(FLAN_MODEL)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_flan = model_flan.to(device)

total_params = sum(p.numel() for p in model_flan.parameters())
trainable_params = sum(p.numel() for p in model_flan.parameters() if p.requires_grad)

print(f"\n=== Info Model FLAN-T5 ===")
print(f"Device    : {device}")
print(f"Total Params    : {total_params:,}")
print(f"Trainable Params: {trainable_params:,}")
print("Model FLAN-T5 siap digunakan!")

Memuat model FLAN-T5: google/flan-t5-base...

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

=== Info Model FLAN-T5 ===
Device    : cuda
Total Params    : 247,577,856
Trainable Params: 247,577,856
Model FLAN-T5 siap digunakan!

In [15]:
print(f"Memuat model IndoBART: {BART_MODEL}...")
model_bart = MBartForConditionalGeneration.from_pretrained(BART_MODEL)
model_bart = model_bart.to(device)

total_params_bart = sum(p.numel() for p in model_bart.parameters())
trainable_params_bart = sum(p.numel() for p in model_bart.parameters() if p.requires_grad)

print(f"\n=== Info Model IndoBART ===")
print(f"Device          : {device}")
print(f"Total Params    : {total_params_bart:,}")
print(f"Trainable Params: {trainable_params_bart:,}")
print("Model IndoBART siap digunakan!")

Memuat model IndoBART: indobenchmark/indobart-v2...

config.json:   0%|          | 0.00/1.71k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/526M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/267 [00:00<?, ?it/s]

=== Info Model IndoBART ===
Device          : cuda
Total Params    : 131,543,040
Trainable Params: 131,543,040
Model IndoBART siap digunakan!

## FLAN-T5

### Metrik Evaluasi

In [16]:
rouge = evaluate.load("rouge")

def compute_metrics_flan(eval_pred):
    predictions, labels = eval_pred

    # Kadang model mereturn tuple, ambil elemen pertamanya
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Ganti secara masif semua nilai -100 menjadi pad_token_id di kedua variabel
    predictions = np.where(predictions != -100, predictions, tokenizer_flan.pad_token_id)
    labels = np.where(labels != -100, labels, tokenizer_flan.pad_token_id)

    # Decode menjadi teks
    decoded_preds = tokenizer_flan.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer_flan.batch_decode(labels, skip_special_tokens=True)

    # Rapikan format baris untuk perhitungan ROUGE
    decoded_preds  = ["\n".join(p.strip().split(".")) for p in decoded_preds]
    decoded_labels = ["\n".join(l.strip().split(".")) for l in decoded_labels]

    # Ingat use_stemmer=False
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=False)

    return {k: round(v, 4) for k, v in result.items()}

data_collator_flan = DataCollatorForSeq2Seq(
    tokenizer=tokenizer_flan,
    model=model_flan,
    padding=True,
    label_pad_token_id=-100
)

model.safetensors:   0%|          | 0.00/526M [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

### Fine-Tune

In [17]:
torch.cuda.empty_cache()
import gc
gc.collect()

training_args_flan = Seq2SeqTrainingArguments(
    output_dir="/content/drive/MyDrive/NLP_Project/flan_t5_results", # UBAH KE DRIVE
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=5,
    weight_decay=0.01,
    predict_with_generate=True,
    generation_max_length=150,
    load_best_model_at_end=True,
    metric_for_best_model="rouge2",
    fp16=False, # Tetap False sesuai perbaikan sebelumnya
    logging_dir="/content/drive/MyDrive/NLP_Project/logs_flan", # UBAH KE DRIVE
    logging_steps=50,
    report_to="none",
    save_total_limit=2, # Tambahan opsional: agar Drive tidak penuh, simpan 2 checkpoint terakhir saja
)

trainer_flan = Seq2SeqTrainer(
    model=model_flan,
    args=training_args_flan,
    train_dataset=tokenized_flan["train"],
    eval_dataset=tokenized_flan["validation"],
    processing_class=tokenizer_flan,
    data_collator=data_collator_flan,
    compute_metrics=compute_metrics_flan,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("=== Memulai/Melanjutkan Fine-Tuning FLAN-T5 ===")
# UBAH BARIS INI: Colab akan otomatis mencari checkpoint di output_dir
trainer_flan.train()
print("\nFine-Tuning FLAN-T5 selesai!")

# Simpan model
trainer_flan.save_model("/content/drive/MyDrive/NLP_Project/flan_t5_finetuned")
tokenizer_flan.save_pretrained("/content/drive/MyDrive/NLP_Project/flan_t5_finetuned")
print("Model FLAN-T5 disimpan ke Drive")

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

=== Memulai/Melanjutkan Fine-Tuning FLAN-T5 ===

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

Fine-Tuning FLAN-T5 selesai!

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model FLAN-T5 disimpan ke Drive

##

## IndoBART

### Metrik Evaluasi

In [18]:
def compute_metrics_bart(eval_pred):
    predictions, labels = eval_pred

    if isinstance(predictions, tuple):
        predictions = predictions[0]

    predictions = np.where(predictions != -100, predictions, tokenizer_bart.pad_token_id)
    labels = np.where(labels != -100, labels, tokenizer_bart.pad_token_id)

    decoded_preds = tokenizer_bart.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer_bart.batch_decode(labels, skip_special_tokens=True)

    decoded_preds  = ["\n".join(p.strip().split(".")) for p in decoded_preds]
    decoded_labels = ["\n".join(l.strip().split(".")) for l in decoded_labels]

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=False)

    return {k: round(v, 4) for k, v in result.items()}

data_collator_bart = DataCollatorForSeq2Seq(
    tokenizer=tokenizer_bart,
    model=model_bart,
    padding=True,
    label_pad_token_id=-100
)

### Fine-Tune

In [19]:
training_args_bart = Seq2SeqTrainingArguments(
    output_dir="/content/drive/MyDrive/NLP_Project/indobart_results", # UBAH KE DRIVE,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=5,
    weight_decay=0.01,
    predict_with_generate=True,
    generation_max_length=150,
    load_best_model_at_end=True,
    metric_for_best_model="rouge2",
    fp16=False, # IndoBART aman pakai True
    logging_dir="/content/drive/MyDrive/NLP_Project/logs_bart", # UBAH KE DRIVE
    logging_steps=50,
    report_to="none",
    save_total_limit=2, # Batasi checkpoint agar Drive tidak penuh
)

trainer_bart = Seq2SeqTrainer(
    model=model_bart,
    args=training_args_bart,
    train_dataset=tokenized_bart["train"],
    eval_dataset=tokenized_bart["validation"],
    processing_class=tokenizer_bart,
    data_collator=data_collator_bart,
    compute_metrics=compute_metrics_bart,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("=== Memulai/Melanjutkan Fine-Tuning IndoBART ===")
# UBAH BARIS INI
trainer_bart.train()
print("\nFine-Tuning IndoBART selesai!")

trainer_bart.save_model("/content/drive/MyDrive/NLP_Project/indobart_finetuned")
tokenizer_bart.save_pretrained("/content/drive/MyDrive/NLP_Project/indobart_finetuned")
print("Model IndoBART disimpan ke Drive")

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

=== Memulai/Melanjutkan Fine-Tuning IndoBART ===

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

Fine-Tuning IndoBART selesai!

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model IndoBART disimpan ke Drive

## Summarization Pipeline

### FLAN-T5

In [20]:
def summarize_with_flan(text, max_length=128, min_length=30, num_beams=4):
    """
    Ringkas teks menggunakan FLAN-T5 fine-tuned.
    Args:
        text       : teks input (str)
        max_length : panjang maksimum ringkasan (token)
        min_length : panjang minimum ringkasan (token)
        num_beams  : lebar beam search
    Returns:
        summary    : ringkasan (str)
    """
    inputs = tokenizer_flan(
        text,
        return_tensors="pt",
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding=True
    ).to(device)

    outputs = model_flan.generate(
        **inputs,
        max_length=max_length,
        min_length=min_length,
        num_beams=num_beams,
        early_stopping=True,
        no_repeat_ngram_size=3,
        length_penalty=2.0
    )
    return tokenizer_flan.decode(outputs[0], skip_special_tokens=True)

### IndoBART

In [21]:
def summarize_with_bart(text, max_length=128, min_length=30, num_beams=4):
    """
    Ringkas teks menggunakan IndoBART fine-tuned.
    """
    inputs = tokenizer_bart(
        text,
        return_tensors="pt",
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding=True
    ).to(device)

    forced_bos = tokenizer_bart.lang_code_to_id.get("id_ID")

    outputs = model_bart.generate(
        **inputs,
        max_length=max_length,
        min_length=min_length,
        num_beams=num_beams,
        early_stopping=True,
        no_repeat_ngram_size=3,
        length_penalty=2.0,
        forced_bos_token_id=forced_bos
    )
    return tokenizer_bart.decode(outputs[0], skip_special_tokens=True)

### Full-Pipeline

In [22]:
def full_summarization_pipeline(text, model_choice="flan",
                                 max_length=150, min_length=30, num_beams=4):
    """
    Pipeline langsung (tanpa chunking)
    """
    summarize_fn = summarize_with_flan if model_choice == "flan" else summarize_with_bart

    # Langsung ringkas teks utuh
    final_summary = summarize_fn(text, max_length=max_length,
                                 min_length=min_length, num_beams=num_beams)

    return final_summary, [final_summary] # Mengembalikan format yang sama agar kode testing di bawahnya tidak error

## Hyperparameter Testing

In [23]:
# ── Definisi grid hyperparameter ─────────────────────────────────────
HYPERPARAM_GRID = {
    "max_length": [64, 128, 200],
    "min_length": [20, 40],
    "num_beams" : [2, 4, 6]
}

# Ambil 5 sampel test
N_SAMPLES = 5
test_samples = dataset_split["test"].select(range(N_SAMPLES))

comparison_results = []

print("=== Mulai Hyperparameter Testing ===")
print(f"Grid: {HYPERPARAM_GRID}")
print(f"Sampel  : {N_SAMPLES} artikel dari test set")
print(f"Model   : FLAN-T5 & IndoBART")
print("-" * 70)

for max_len, min_len, beams in itertools.product(
    HYPERPARAM_GRID["max_length"],
    HYPERPARAM_GRID["min_length"],
    HYPERPARAM_GRID["num_beams"]
):
    # Lewati kombinasi tidak valid
    if min_len >= max_len:
        continue

    for model_choice in ["flan", "bart"]:
        flan_scores, bart_scores_r = [], []
        latencies = []

        for sample in test_samples:
            t_start = time.time()
            pred, _ = full_summarization_pipeline(
                sample["text"],
                model_choice=model_choice,
                max_length=max_len,
                min_length=min_len,
                num_beams=beams
            )
            latencies.append(time.time() - t_start)

            score = rouge.compute(
                predictions=[pred],
                references=[sample["summary"]],
                use_stemmer=False
            )
            flan_scores.append(score["rouge2"])

        avg_r2  = round(sum(flan_scores) / len(flan_scores), 4)
        avg_lat = round(sum(latencies) / len(latencies), 2)

        comparison_results.append({
            "model"      : model_choice.upper(),
            "max_length" : max_len,
            "min_length" : min_len,
            "num_beams"  : beams,
            "rouge2_avg" : avg_r2,
            "latency_s"  : avg_lat
        })

        print(f"[{model_choice.upper():8s}] max={max_len:3d} min={min_len:2d} beams={beams} | ROUGE-2={avg_r2:.4f} | latency={avg_lat:.2f}s")

df_hyperparam = pd.DataFrame(comparison_results)
print("\n=== Tabel Perbandingan Hyperparameter ===")
display(df_hyperparam.sort_values(["model", "rouge2_avg"], ascending=[True, False]))

=== Mulai Hyperparameter Testing ===
Grid: {'max_length': [64, 128, 200], 'min_length': [20, 40], 'num_beams': [2, 4, 6]}
Sampel  : 5 artikel dari test set
Model   : FLAN-T5 & IndoBART
----------------------------------------------------------------------
[FLAN    ] max= 64 min=20 beams=2 | ROUGE-2=0.1232 | latency=2.46s
[BART    ] max= 64 min=20 beams=2 | ROUGE-2=0.0520 | latency=1.06s
[FLAN    ] max= 64 min=20 beams=4 | ROUGE-2=0.1328 | latency=2.32s
[BART    ] max= 64 min=20 beams=4 | ROUGE-2=0.0573 | latency=0.92s
[FLAN    ] max= 64 min=20 beams=6 | ROUGE-2=0.1158 | latency=1.93s
[BART    ] max= 64 min=20 beams=6 | ROUGE-2=0.0531 | latency=1.04s
[FLAN    ] max= 64 min=40 beams=2 | ROUGE-2=0.1232 | latency=1.61s
[BART    ] max= 64 min=40 beams=2 | ROUGE-2=0.0520 | latency=0.93s
[FLAN    ] max= 64 min=40 beams=4 | ROUGE-2=0.1328 | latency=1.72s
[BART    ] max= 64 min=40 beams=4 | ROUGE-2=0.0573 | latency=0.94s
[FLAN    ] max= 64 min=40 beams=6 | ROUGE-2=0.1158 | latency=2.02s
[BART    ] max= 64 min=40 beams=6 | ROUGE-2=0.0531 | latency=0.87s
[FLAN    ] max=128 min=20 beams=2 | ROUGE-2=0.1498 | latency=2.89s
[BART    ] max=128 min=20 beams=2 | ROUGE-2=0.1065 | latency=1.73s
[FLAN    ] max=128 min=20 beams=4 | ROUGE-2=0.1580 | latency=3.22s
[BART    ] max=128 min=20 beams=4 | ROUGE-2=0.0673 | latency=1.77s
[FLAN    ] max=128 min=20 beams=6 | ROUGE-2=0.1599 | latency=3.71s
[BART    ] max=128 min=20 beams=6 | ROUGE-2=0.0690 | latency=1.90s
[FLAN    ] max=128 min=40 beams=2 | ROUGE-2=0.1498 | latency=2.82s
[BART    ] max=128 min=40 beams=2 | ROUGE-2=0.1065 | latency=1.72s
[FLAN    ] max=128 min=40 beams=4 | ROUGE-2=0.1580 | latency=3.17s
[BART    ] max=128 min=40 beams=4 | ROUGE-2=0.0673 | latency=1.79s
[FLAN    ] max=128 min=40 beams=6 | ROUGE-2=0.1599 | latency=3.76s
[BART    ] max=128 min=40 beams=6 | ROUGE-2=0.0690 | latency=1.91s
[FLAN    ] max=200 min=20 beams=2 | ROUGE-2=0.1578 | latency=3.05s
[BART    ] max=200 min=20 beams=2 | ROUGE-2=0.1053 | latency=1.95s
[FLAN    ] max=200 min=20 beams=4 | ROUGE-2=0.1576 | latency=3.32s
[BART    ] max=200 min=20 beams=4 | ROUGE-2=0.0796 | latency=2.08s
[FLAN    ] max=200 min=20 beams=6 | ROUGE-2=0.1576 | latency=4.24s
[BART    ] max=200 min=20 beams=6 | ROUGE-2=0.0781 | latency=2.13s
[FLAN    ] max=200 min=40 beams=2 | ROUGE-2=0.1578 | latency=3.11s
[BART    ] max=200 min=40 beams=2 | ROUGE-2=0.1053 | latency=1.93s
[FLAN    ] max=200 min=40 beams=4 | ROUGE-2=0.1576 | latency=3.36s
[BART    ] max=200 min=40 beams=4 | ROUGE-2=0.0796 | latency=2.02s
[FLAN    ] max=200 min=40 beams=6 | ROUGE-2=0.1576 | latency=4.48s
[BART    ] max=200 min=40 beams=6 | ROUGE-2=0.0781 | latency=2.29s

=== Tabel Perbandingan Hyperparameter ===

   model  max_length  min_length  num_beams  rouge2_avg  latency_s
13  BART         128          20          2      0.1065       1.73
19  BART         128          40          2      0.1065       1.72
25  BART         200          20          2      0.1053       1.95
31  BART         200          40          2      0.1053       1.93
27  BART         200          20          4      0.0796       2.08
33  BART         200          40          4      0.0796       2.02
29  BART         200          20          6      0.0781       2.13
35  BART         200          40          6      0.0781       2.29
17  BART         128          20          6      0.0690       1.90
23  BART         128          40          6      0.0690       1.91
15  BART         128          20          4      0.0673       1.77
21  BART         128          40          4      0.0673       1.79
3   BART          64          20          4      0.0573       0.92
9   BART          64          40          4      0.0573       0.94
5   BART          64          20          6      0.0531       1.04
11  BART          64          40          6      0.0531       0.87
1   BART          64          20          2      0.0520       1.06
7   BART          64          40          2      0.0520       0.93
16  FLAN         128          20          6      0.1599       3.71
22  FLAN         128          40          6      0.1599       3.76
14  FLAN         128          20          4      0.1580       3.22
20  FLAN         128          40          4      0.1580       3.17
24  FLAN         200          20          2      0.1578       3.05
30  FLAN         200          40          2      0.1578       3.11
26  FLAN         200          20          4      0.1576       3.32
28  FLAN         200          20          6      0.1576       4.24
32  FLAN         200          40          4      0.1576       3.36
34  FLAN         200          40          6      0.1576       4.48
12  FLAN         128          20          2      0.1498       2.89
18  FLAN         128          40          2      0.1498       2.82
2   FLAN          64          20          4      0.1328       2.32
8   FLAN          64          40          4      0.1328       1.72
0   FLAN          64          20          2      0.1232       2.46
6   FLAN          64          40          2      0.1232       1.61
4   FLAN          64          20          6      0.1158       1.93
10  FLAN          64          40          6      0.1158       2.02

## Testing

In [24]:
# ── Cari konfigurasi terbaik per model ───────────────────────────────
best_flan = df_hyperparam[df_hyperparam["model"] == "FLAN"] \
    .sort_values("rouge2_avg", ascending=False).iloc[0]
best_bart = df_hyperparam[df_hyperparam["model"] == "BART"] \
    .sort_values("rouge2_avg", ascending=False).iloc[0]

print("=== Konfigurasi Terbaik ===")
print(f"FLAN-T5 : max={int(best_flan.max_length)} min={int(best_flan.min_length)} beams={int(best_flan.num_beams)} | ROUGE-2={best_flan.rouge2_avg}")
print(f"IndoBART: max={int(best_bart.max_length)} min={int(best_bart.min_length)} beams={int(best_bart.num_beams)} | ROUGE-2={best_bart.rouge2_avg}")

# ── Generate ringkasan test set ───────────────────────────────────────
results = []
print("\n=== Menghasilkan Ringkasan Test Set ===")

for i, sample in enumerate(dataset_split["test"]):
    flan_summary, _ = full_summarization_pipeline(
        sample["text"], model_choice="flan",
        max_length=int(best_flan.max_length),
        min_length=int(best_flan.min_length),
        num_beams=int(best_flan.num_beams)
    )
    bart_summary, _ = full_summarization_pipeline(
        sample["text"], model_choice="bart",
        max_length=int(best_bart.max_length),
        min_length=int(best_bart.min_length),
        num_beams=int(best_bart.num_beams)
    )
    results.append({
        "id"               : i + 1,
        "input_text"       : sample["text"][:200] + "...",
        "reference_summary": sample["summary"],
        "flan_summary"     : flan_summary,
        "bart_summary"     : bart_summary
    })

    if (i + 1) % 10 == 0:
        print(f"  → {i+1}/{len(dataset_split['test'])} sampel diproses")

df_results = pd.DataFrame(results)
print(f"\nTotal ringkasan dihasilkan: {len(df_results)}")
display(df_results.head(3))

=== Konfigurasi Terbaik ===
FLAN-T5 : max=128 min=40 beams=6 | ROUGE-2=0.1599
IndoBART: max=128 min=20 beams=2 | ROUGE-2=0.1065

=== Menghasilkan Ringkasan Test Set ===
  → 10/323 sampel diproses
  → 20/323 sampel diproses
  → 30/323 sampel diproses
  → 40/323 sampel diproses
  → 50/323 sampel diproses
  → 60/323 sampel diproses
  → 70/323 sampel diproses
  → 80/323 sampel diproses
  → 90/323 sampel diproses
  → 100/323 sampel diproses
  → 110/323 sampel diproses
  → 120/323 sampel diproses
  → 130/323 sampel diproses
  → 140/323 sampel diproses
  → 150/323 sampel diproses
  → 160/323 sampel diproses
  → 170/323 sampel diproses
  → 180/323 sampel diproses
  → 190/323 sampel diproses
  → 200/323 sampel diproses
  → 210/323 sampel diproses
  → 220/323 sampel diproses
  → 230/323 sampel diproses
  → 240/323 sampel diproses
  → 250/323 sampel diproses
  → 260/323 sampel diproses
  → 270/323 sampel diproses
  → 280/323 sampel diproses
  → 290/323 sampel diproses
  → 300/323 sampel diproses
  → 310/323 sampel diproses
  → 320/323 sampel diproses

Total ringkasan dihasilkan: 323

,id,input_text,reference_summary,flan_summary,bart_summary
0,1,"Judul: sejarah, pemanfaatan, serta dampak indu...",Sejarah nikel dimulai lebih dari 2.000 tahun y...,Nikel pertama kali ditemukan lebih dari 2.000 ...,ikel ertama kali diidentifikasi oleh aron resi...
1,2,Judul: kasus dan penanganan penyakit mulut dan...,Penyakit Mulut dan Kuku (PMK) adalah penyakit ...,Penyakit mulut dan kuku di luar Jawa terbatas ...,enyakit ulut an uku di ndonesia memiliki sejar...
2,3,Judul: jalur mandiri masuk perguruan tinggi ne...,Perguruan Tinggi Negeri (PTN) di Indonesia mem...,Seleksi Jalur Mandiri masuk Perguruan Tingi Ne...,alur andiri asuk erguruan inggi egeri () adala...

In [25]:
# ── Simpan ke CSV ─────────────────────────────────────────────────────
CSV_PATH = "/content/drive/MyDrive/NLP_Project/generated_summaries.csv" # <--- UBAH INI
df_results.to_csv(CSV_PATH, index=False, encoding="utf-8-sig")
print(f"Ringkasan disimpan ke CSV: {CSV_PATH}")

# ── Simpan ke TXT ─────────────────────────────────────────────────────
TXT_PATH = "/content/drive/MyDrive/NLP_Project/generated_summaries.txt" # <--- UBAH INI
with open(TXT_PATH, "w", encoding="utf-8") as f:
    for _, row in df_results.iterrows():
        f.write(f"{'='*70}\n")
        f.write(f"ID         : {row['id']}\n")
        f.write(f"INPUT      : {row['input_text']}\n")
        f.write(f"REFERENSI  : {row['reference_summary']}\n")
        f.write(f"FLAN-T5    : {row['flan_summary']}\n")
        f.write(f"IndoBART   : {row['bart_summary']}\n")
        f.write("\n")
print(f"Ringkasan disimpan ke TXT : {TXT_PATH}")

Ringkasan disimpan ke CSV: /content/drive/MyDrive/NLP_Project/generated_summaries.csv
Ringkasan disimpan ke TXT : /content/drive/MyDrive/NLP_Project/generated_summaries.txt

## Evaluasi

In [26]:
# ── Hitung ROUGE lengkap untuk semua hasil ───────────────────────────
rouge_full = evaluate.load("rouge")

flan_preds = df_results["flan_summary"].tolist()
bart_preds = df_results["bart_summary"].tolist()
refs       = df_results["reference_summary"].tolist()

scores_flan = rouge_full.compute(predictions=flan_preds, references=refs, use_stemmer=False)
scores_bart = rouge_full.compute(predictions=bart_preds, references=refs, use_stemmer=False)

avg_len_flan = round(sum(len(s.split()) for s in flan_preds) / len(flan_preds), 1)
avg_len_bart = round(sum(len(s.split()) for s in bart_preds) / len(bart_preds), 1)
avg_len_ref  = round(sum(len(s.split()) for s in refs)       / len(refs),       1)

comparison_table = pd.DataFrame([
    {
        "Model"          : "FLAN-T5 (fine-tuned)",
        "ROUGE-1"        : round(scores_flan["rouge1"],  4),
        "ROUGE-2"        : round(scores_flan["rouge2"],  4),
        "ROUGE-L"        : round(scores_flan["rougeL"],  4),
        "Avg Length (kata)" : avg_len_flan,
        "Best max_length" : int(best_flan.max_length),
        "Best num_beams"  : int(best_flan.num_beams),
    },
    {
        "Model"          : "IndoBART (fine-tuned)",
        "ROUGE-1"        : round(scores_bart["rouge1"],  4),
        "ROUGE-2"        : round(scores_bart["rouge2"],  4),
        "ROUGE-L"        : round(scores_bart["rougeL"],  4),
        "Avg Length (kata)" : avg_len_bart,
        "Best max_length" : int(best_bart.max_length),
        "Best num_beams"  : int(best_bart.num_beams),
    },
    {
        "Model"          : "Reference Summary",
        "ROUGE-1"        : "-",
        "ROUGE-2"        : "-",
        "ROUGE-L"        : "-",
        "Avg Length (kata)" : avg_len_ref,
        "Best max_length" : "-",
        "Best num_beams"  : "-",
    }
])

print("=" * 70)
print("MODEL COMPARISON RAW OUTPUT")
print("=" * 70)
display(comparison_table)

# Simpan tabel ke CSV
comparison_table.to_csv("/content/drive/MyDrive/NLP_Project/model_comparison.csv", index=False, encoding="utf-8-sig") # <--- UBAH INI
print("\nTabel disimpan ke model_comparison.csv di Drive")

# ── Ringkasan Kesimpulan ──────────────────────────────────────────────
winner = "FLAN-T5" if scores_flan["rouge2"] >= scores_bart["rouge2"] else "IndoBART"
print(f"\n>>> Model dengan ROUGE-2 terbaik: {winner}")

======================================================================
MODEL COMPARISON RAW OUTPUT
======================================================================

,Model,ROUGE-1,ROUGE-2,ROUGE-L,Avg Length (kata),Best max_length,Best num_beams
0,FLAN-T5 (fine-tuned),0.2989,0.1578,0.2317,38.5,128,6
1,IndoBART (fine-tuned),0.203,0.0815,0.1503,38.0,128,2
2,Reference Summary,-,-,-,106.2,-,-

Tabel disimpan ke model_comparison.csv di Drive

>>> Model dengan ROUGE-2 terbaik: FLAN-T5