In [ ]:
!pip install requests beautifulsoup4 pandas --quiet

In [ ]:
import re
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from typing import Optional
import csv

In [ ]:
BASE_BLOG = "https://www.ruangguru.com/blog"
BASE_API  = "https://www.ruangguru.com/blog/wp-json/wp/v2"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}

CATEGORY_URLS = [
    f"{BASE_BLOG}/c/sejarah/sejarah-smp-kelas-{k}" for k in range(7, 10)
] + [
    f"{BASE_BLOG}/c/sejarah/sejarah-sma-kelas-{k}" for k in range(10, 13)
]

print("Target category URLs:")
for url in CATEGORY_URLS:
    print(f"  {url}")

Target category URLs:
  https://www.ruangguru.com/blog/c/sejarah/sejarah-smp-kelas-7
  https://www.ruangguru.com/blog/c/sejarah/sejarah-smp-kelas-8
  https://www.ruangguru.com/blog/c/sejarah/sejarah-smp-kelas-9
  https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-10
  https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-11
  https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-12

In [ ]:
def get_last_page_number(soup) -> int:
    max_page = 1
    for a in soup.find_all("a", href=True):
        match = re.search(r"/page/(\d+)/?$", a["href"])
        if match:
            page_num = int(match.group(1))
            if page_num > max_page:
                max_page = page_num
    return max_page


def extract_slugs_from_soup(soup, category_label: str) -> list:
    results = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if not href.startswith(f"{BASE_BLOG}/"):
            continue
        path = href.replace(BASE_BLOG, "").lstrip("/")
        if any(path.startswith(p) for p in ["c/", "tag/", "#", "?", "page/"]):
            continue
        if not path:
            continue
        results.append({
            "slug":            path.rstrip("/"),
            "url":             href,
            "source_category": category_label,
        })
    return results


def get_all_slugs_from_category(base_category_url: str) -> list:
    category_label = base_category_url.rstrip("/").split("/")[-1]
    all_slugs = {}

    try:
        r = requests.get(base_category_url, headers=HEADERS, timeout=15)
        r.raise_for_status()
    except requests.RequestException as e:
        print(f"Cannot fetch {base_category_url}: {e}")
        return []

    soup = BeautifulSoup(r.text, "html.parser")
    last_page = get_last_page_number(soup)
    print(f"  📄 {category_label}: {last_page} page(s) detected")

    for item in extract_slugs_from_soup(soup, category_label):
        all_slugs[item["slug"]] = item

    # page 2 - n
    for page_num in range(2, last_page + 1):
        page_url = f"{base_category_url}/page/{page_num}"
        print(f"     → Fetching page {page_num}/{last_page}: {page_url}")
        try:
            r = requests.get(page_url, headers=HEADERS, timeout=15)
            r.raise_for_status()
        except requests.RequestException as e:
            print(f"Failed: {e}")
            break

        soup = BeautifulSoup(r.text, "html.parser")
        for item in extract_slugs_from_soup(soup, category_label):
            all_slugs[item["slug"]] = item

        time.sleep(0.8)

    print(f"{len(all_slugs)} unique article(s) from {category_label}")
    return list(all_slugs.values())

In [ ]:
all_articles_seed = []
global_seen_slugs = set()

for cat_url in CATEGORY_URLS:
    articles = get_all_slugs_from_category(cat_url)
    for art in articles:
        if art["slug"] not in global_seen_slugs:
            global_seen_slugs.add(art["slug"])
            all_articles_seed.append(art)
    time.sleep(1.0)

print(f"\nGrand total unique article slugs: {len(all_articles_seed)}")
df_seed = pd.DataFrame(all_articles_seed)
print(df_seed["source_category"].value_counts().to_string())
df_seed.head(10)

  📄 sejarah-smp-kelas-7: 1 page(s) detected
4 unique article(s) from sejarah-smp-kelas-7
  📄 sejarah-smp-kelas-8: 1 page(s) detected
4 unique article(s) from sejarah-smp-kelas-8
  📄 sejarah-smp-kelas-9: 2 page(s) detected
     → Fetching page 2/2: https://www.ruangguru.com/blog/c/sejarah/sejarah-smp-kelas-9/page/2
13 unique article(s) from sejarah-smp-kelas-9
  📄 sejarah-sma-kelas-10: 5 page(s) detected
     → Fetching page 2/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-10/page/2
     → Fetching page 3/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-10/page/3
     → Fetching page 4/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-10/page/4
     → Fetching page 5/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-10/page/5
42 unique article(s) from sejarah-sma-kelas-10
  📄 sejarah-sma-kelas-11: 5 page(s) detected
     → Fetching page 2/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-11/page/2
     → Fetching page 3/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-11/page/3
     → Fetching page 4/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-11/page/4
     → Fetching page 5/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-11/page/5
49 unique article(s) from sejarah-sma-kelas-11
  📄 sejarah-sma-kelas-12: 5 page(s) detected
     → Fetching page 2/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-12/page/2
     → Fetching page 3/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-12/page/3
     → Fetching page 4/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-12/page/4
     → Fetching page 5/5: https://www.ruangguru.com/blog/c/sejarah/sejarah-sma-kelas-12/page/5
49 unique article(s) from sejarah-sma-kelas-12

Grand total unique article slugs: 161
source_category
sejarah-sma-kelas-11    49
sejarah-sma-kelas-12    49
sejarah-sma-kelas-10    42
sejarah-smp-kelas-9     13
sejarah-smp-kelas-8      4
sejarah-smp-kelas-7      4

,slug,url,source_category
0,kerajaan-samudera-pasai,https://www.ruangguru.com/blog/kerajaan-samude...,sejarah-smp-kelas-7
1,sejarah-nenek-moyang-bangsa-indonesia,https://www.ruangguru.com/blog/sejarah-nenek-m...,sejarah-smp-kelas-7
2,manusia-dan-dinosaurus,https://www.ruangguru.com/blog/manusia-dan-din...,sejarah-smp-kelas-7
3,perang-saudara-kerajaan-kediri,https://www.ruangguru.com/blog/perang-saudara-...,sejarah-smp-kelas-7
4,masa-penjajahan,https://www.ruangguru.com/blog/masa-penjajahan,sejarah-smp-kelas-8
5,kedatangan-nica-di-indonesia,https://www.ruangguru.com/blog/kedatangan-nica...,sejarah-smp-kelas-8
6,kedatangan-pasukan-afnei-di-indonesia,https://www.ruangguru.com/blog/kedatangan-pasu...,sejarah-smp-kelas-8
7,tahukah-kamu-mengenai-organisasi-pergerakan-in...,https://www.ruangguru.com/blog/tahukah-kamu-me...,sejarah-smp-kelas-8
8,sejarah-kelahiran-masa-orde-baru,https://www.ruangguru.com/blog/sejarah-kelahir...,sejarah-smp-kelas-9
9,mengenal-perjanjian-renville,https://www.ruangguru.com/blog/mengenal-perjan...,sejarah-smp-kelas-9

In [ ]:
def fetch_post_by_slug(slug: str) -> Optional[dict]:
    """
    Hits WP REST API with ?slug=<slug>.
    Returns structured dict or None on failure.
    """
    url    = f"{BASE_API}/posts"
    params = {
        "slug":    slug,
        "_fields": "id,slug,title,link,date,content,excerpt",
    }
    try:
        r = requests.get(url, params=params, headers=HEADERS, timeout=15)
        r.raise_for_status()
        data = r.json()
    except requests.RequestException as e:
        print(f"    API error for slug '{slug}': {e}")
        return None

    if not data:
        print(f"    Slug not found in API: '{slug}'")
        return None

    post = data[0]
    return {
        "id":      post.get("id"),
        "slug":    post.get("slug"),
        "title":   post["title"]["rendered"],
        "url":     post.get("link"),
        "date":    post.get("date"),
        "content": post["content"]["rendered"],
        "excerpt": post["excerpt"]["rendered"],
    }


def strip_html(html: str) -> str:
    """
    Cleans WP API content HTML into pure article prose.
    Outputs a single continuous paragraph per article (CSV-safe).
    """
    soup = BeautifulSoup(html, "html.parser")

    NOISE_TAGS = [
        "img", "figure", "figcaption", "picture",
        "video", "audio", "iframe",
        "script", "style", "noscript",
        "button", "form", "input",
        "svg", "canvas",
        "nav", "aside", "footer", "header",
        "advertisement",
    ]
    for tag in soup.find_all(NOISE_TAGS):
        tag.decompose()

    NOISE_PATTERNS = [
        "shortcode", "widget", "banner", "promo", "cta",
        "related", "recommendation", "sidebar", "ads", "advertisement",
        "social-share", "share-button", "newsletter", "popup",
        "breadcrumb", "tag-list", "author-box",
    ]
    for pattern in NOISE_PATTERNS:
        for tag in soup.find_all(
            True,
            class_=lambda c: c and pattern in " ".join(c).lower()
        ):
            tag.decompose()

    BLOCK_TAGS = [
        "p", "div", "h1", "h2", "h3", "h4", "h5", "h6",
        "li", "br", "tr", "blockquote", "hr", "section",
        "ul", "ol", "table", "thead", "tbody",
    ]
    for tag in soup.find_all(BLOCK_TAGS):
        tag.insert_before(" ")
        tag.insert_after(" ")

    text = soup.get_text(separator="")

    text = re.sub(r"[\n\r\t]+", " ", text)    # newlines/tabs → space
    text = re.sub(r" {2,}", " ", text)         # multi-space → single space

    text = re.sub(r"\[.*?\]", "", text)        # remove [caption], [gallery], etc.
    text = re.sub(r" {2,}", " ", text)         # re-collapse after shortcode removal

    return text.strip()

In [ ]:
enriched_records = []
total = len(all_articles_seed)

for i, item in enumerate(all_articles_seed, start=1):
    slug     = item["slug"]
    category = item["source_category"]
    print(f"[{i:>3}/{total}] Fetching: {slug}  ({category})")

    post_data = fetch_post_by_slug(slug)
    if post_data:
        post_data["source_category"] = category
        post_data["content_clean"]   = strip_html(post_data["content"])
        post_data["excerpt_clean"]   = strip_html(post_data["excerpt"])
        enriched_records.append(post_data)

    time.sleep(0.6)

print(f"\n Successfully fetched: {len(enriched_records)} / {total} articles")

[  1/161] Fetching: kerajaan-samudera-pasai  (sejarah-smp-kelas-7)
[  2/161] Fetching: sejarah-nenek-moyang-bangsa-indonesia  (sejarah-smp-kelas-7)
[  3/161] Fetching: manusia-dan-dinosaurus  (sejarah-smp-kelas-7)
[  4/161] Fetching: perang-saudara-kerajaan-kediri  (sejarah-smp-kelas-7)
[  5/161] Fetching: masa-penjajahan  (sejarah-smp-kelas-8)
[  6/161] Fetching: kedatangan-nica-di-indonesia  (sejarah-smp-kelas-8)
[  7/161] Fetching: kedatangan-pasukan-afnei-di-indonesia  (sejarah-smp-kelas-8)
[  8/161] Fetching: tahukah-kamu-mengenai-organisasi-pergerakan-indonesia  (sejarah-smp-kelas-8)
[  9/161] Fetching: sejarah-kelahiran-masa-orde-baru  (sejarah-smp-kelas-9)
[ 10/161] Fetching: mengenal-perjanjian-renville  (sejarah-smp-kelas-9)
[ 11/161] Fetching: tokoh-kemerdekaan-dan-revolusi-indonesia  (sejarah-smp-kelas-9)
[ 12/161] Fetching: republik-indonesia-serikat  (sejarah-smp-kelas-9)
[ 13/161] Fetching: 5-bentuk-penyimpangan-demokrasi-terpimpin-terhadap-politik-luar-negeri  (sejarah-smp-kelas-9)
[ 14/161] Fetching: mengenal-masa-reformasi-di-indonesia  (sejarah-smp-kelas-9)
[ 15/161] Fetching: perjanjian-linggajati  (sejarah-smp-kelas-9)
[ 16/161] Fetching: 7-penyimpangan-demokrasi-terpimpin-terhadap-pancasila-dan-uud-1945  (sejarah-smp-kelas-9)
[ 17/161] Fetching: perjuangan-bersenjata-untuk-mempertahankan-kemerdekaan-indonesia  (sejarah-smp-kelas-9)
[ 18/161] Fetching: ips-kelas-9-mengenal-suku-bangsa-di-dunia  (sejarah-smp-kelas-9)
[ 19/161] Fetching: faktor-penyebab-belanda-keluar-dari-indonesia  (sejarah-smp-kelas-9)
[ 20/161] Fetching: kerugian-indonesia-pada-perjanjian-renville  (sejarah-smp-kelas-9)
[ 21/161] Fetching: perundingan-hooge-veluwe-upaya-indonesia-pertahankan-kemerdekaan  (sejarah-smp-kelas-9)
[ 22/161] Fetching: sejarah-kesultanan-banten  (sejarah-sma-kelas-10)
[ 23/161] Fetching: sejarah-kerajaan-mataram-islam  (sejarah-sma-kelas-10)
[ 24/161] Fetching: sejarah-kesultanan-demak  (sejarah-sma-kelas-10)
[ 25/161] Fetching: sejarah-kelas-10-asal-usul-dan-kisah-peradaban-awal-amerika  (sejarah-sma-kelas-10)
[ 26/161] Fetching: peradaban-romawi-kuno  (sejarah-sma-kelas-10)
[ 27/161] Fetching: peradaban-tiongkok-kuno  (sejarah-sma-kelas-10)
[ 28/161] Fetching: peradaban-india-kuno  (sejarah-sma-kelas-10)
[ 29/161] Fetching: peradaban-yunani-kuno  (sejarah-sma-kelas-10)
[ 30/161] Fetching: sejarah-mesir-kuno  (sejarah-sma-kelas-10)
[ 31/161] Fetching: peradaban-mesopotamia  (sejarah-sma-kelas-10)
[ 32/161] Fetching: 4-teori-masuknya-islam-ke-nusantara  (sejarah-sma-kelas-10)
[ 33/161] Fetching: sejarah-kerajaan-aceh  (sejarah-sma-kelas-10)
[ 34/161] Fetching: peralatan-manusia-purba  (sejarah-sma-kelas-10)
[ 35/161] Fetching: perjalanan-panjang-manusia-modern  (sejarah-sma-kelas-10)
[ 36/161] Fetching: pembabakan-zaman-praaksara-berdasarkan-arkeologi  (sejarah-sma-kelas-10)
[ 37/161] Fetching: pembabakan-zaman-praaksara-berdasarkan-geologi  (sejarah-sma-kelas-10)
[ 38/161] Fetching: pengertian-sejarah  (sejarah-sma-kelas-10)
[ 39/161] Fetching: menangkal-hoax-dengan-cara-berpikir-diakronik-dan-sinkronik  (sejarah-sma-kelas-10)
[ 40/161] Fetching: pengaruh-islam-di-kehidupan-masa-kini  (sejarah-sma-kelas-10)
[ 41/161] Fetching: kerajaan-hindu-buddha-jenggala-dan-kediri-singasari-majapahit  (sejarah-sma-kelas-10)
[ 42/161] Fetching: sejarah-kerajaan-maritim-hindu-buddha-sriwijaya-mataram-medang-kamulan  (sejarah-sma-kelas-10)
[ 43/161] Fetching: sejarah-kerajaan-maritim-hindu-buddha-kutai-tarumanegara-kalingga  (sejarah-sma-kelas-10)
[ 44/161] Fetching: pengaruh-hindu-dan-buddha  (sejarah-sma-kelas-10)
[ 45/161] Fetching: sistem-kepercayaan-manusia-purba  (sejarah-sma-kelas-10)
[ 46/161] Fetching: pola-kehidupan-menetap-masyarakat-zaman-praaksara  (sejarah-sma-kelas-10)
[ 47/161] Fetching: apa-maksud-sejarah-sebagai-ilmu-dan-seni  (sejarah-sma-kelas-10)
[ 48/161] Fetching: makna-di-balik-pentingnya-perubahan-dan-keberlanjutan  (sejarah-sma-kelas-10)
[ 49/161] Fetching: pengertian-sejarah-sebagai-kisah-dan-peristiwa  (sejarah-sma-kelas-10)
[ 50/161] Fetching: jalur-rempah  (sejarah-sma-kelas-10)
[ 51/161] Fetching: historiografi-sejarah  (sejarah-sma-kelas-10)
[ 52/161] Fetching: manusia-purba  (sejarah-sma-kelas-10)
[ 53/161] Fetching: manusia-purba-indonesia  (sejarah-sma-kelas-10)
[ 54/161] Fetching: bagaimana-melakukan-penelitian-sejarah  (sejarah-sma-kelas-10)
[ 55/161] Fetching: jenis-jenis-sumber-sejarah  (sejarah-sma-kelas-10)
[ 56/161] Fetching: bagaimana-konsep-kehidupan-manusia-dalam-ruang-dan-waktu  (sejarah-sma-kelas-10)
[ 57/161] Fetching: proses-masuknya-agama-hindu-buddha-ke-nusantara  (sejarah-sma-kelas-10)
[ 58/161] Fetching: olimpiade-yunani-kuno  (sejarah-sma-kelas-10)
[ 59/161] Fetching: peradaban-mesir-kuno  (sejarah-sma-kelas-10)
[ 60/161] Fetching: sejarah-tahun  (sejarah-sma-kelas-10)
[ 61/161] Fetching: aspek-kepercayaan-masa-praaksara  (sejarah-sma-kelas-10)
[ 62/161] Fetching: ekonomi-praaksara  (sejarah-sma-kelas-10)
[ 63/161] Fetching: bagaimana-manusia-tanpa-peradaban-mesopotamia  (sejarah-sma-kelas-10)
[ 64/161] Fetching: sejarah-hari-kebangkitan-nasional  (sejarah-sma-kelas-11)
[ 65/161] Fetching: kehidupan-masyarakat-di-masa-kerajaan-islam  (sejarah-sma-kelas-11)
[ 66/161] Fetching: sejarah-kelas-11-dampak-kedatangan-bangsa-eropa-bagi-indonesia  (sejarah-sma-kelas-11)
[ 67/161] Fetching: seri-revolusi-dunia-revolusi-rusia  (sejarah-sma-kelas-11)
[ 68/161] Fetching: pergerakan-nasional-indonesia  (sejarah-sma-kelas-11)
[ 69/161] Fetching: liga-bangsa-bangsa  (sejarah-sma-kelas-11)
[ 70/161] Fetching: sejarah-perang-dunia-1  (sejarah-sma-kelas-11)
[ 71/161] Fetching: sejarah-perserikatan-bangsa-bangsa-pbb  (sejarah-sma-kelas-11)
[ 72/161] Fetching: pengertian-kolonialisme-dan-imperialisme  (sejarah-sma-kelas-11)
[ 73/161] Fetching: imperialisme-dan-kolonialisme  (sejarah-sma-kelas-11)
[ 74/161] Fetching: revolusi-amerika  (sejarah-sma-kelas-11)
[ 75/161] Fetching: pan-islamisme  (sejarah-sma-kelas-11)
[ 76/161] Fetching: tanam-paksa  (sejarah-sma-kelas-11)
[ 77/161] Fetching: perlawanan-indonesia-terhadap-portugis-dan-voc  (sejarah-sma-kelas-11)
[ 78/161] Fetching: sejarah-kelas-11-perkembangan-kolonialisme-dan-imperialisme-eropa-di-indonesia  (sejarah-sma-kelas-11)
[ 79/161] Fetching: detik-detik-menuju-proklamasi-kemerdekaan-ri  (sejarah-sma-kelas-11)
[ 80/161] Fetching: kekalahan-kekalahan-jepang  (sejarah-sma-kelas-11)
[ 81/161] Fetching: kerajaan-kerajaan-maritim-islam-di-nusantara  (sejarah-sma-kelas-11)
[ 82/161] Fetching: pemikiran-piagam-pbb-dalam-upaya-menciptakan-keamanan-dan-perdamaian-dunia  (sejarah-sma-kelas-11)
[ 83/161] Fetching: nasionalisme-dan-demokrasi-di-indonesia  (sejarah-sma-kelas-11)
[ 84/161] Fetching: sejarah-kelas-11-bentuk-strategi-perjuangan-pascakemerdekaan  (sejarah-sma-kelas-11)
[ 85/161] Fetching: sejarah-kelas-11-ide-dan-pemikiran-pemikiran-proklamasi-kemerdekaan-indonesia-1945  (sejarah-sma-kelas-11)
[ 86/161] Fetching: dampak-pendudukan-jepang-di-indonesia  (sejarah-sma-kelas-11)
[ 87/161] Fetching: proses-dan-latar-belakang-pendudukan-jepang-di-indonesia  (sejarah-sma-kelas-11)
[ 88/161] Fetching: organisasi-militer-jepang-yang-didirikan-di-indonesia  (sejarah-sma-kelas-11)
[ 89/161] Fetching: perang-dunia-2  (sejarah-sma-kelas-11)
[ 90/161] Fetching: sejarah-kelas-11-mengenal-organisasi-kebangsaan-budi-utomo-sarekat-islam-indische-partij  (sejarah-sma-kelas-11)
[ 91/161] Fetching: strategi-perlawanan-bangsa-indonesia-terhadap-penjajahan-belanda  (sejarah-sma-kelas-11)
[ 92/161] Fetching: sejarah-sumpah-pemuda  (sejarah-sma-kelas-11)
[ 93/161] Fetching: sejarah-kelas-11-hubungan-politik-etis-dengan-tumbuhnya-kesadaran-kebangsaan-indonesia  (sejarah-sma-kelas-11)
[ 94/161] Fetching: apa-yang-dimaksud-dengan-sistem-ekonomi-merkantilisme  (sejarah-sma-kelas-11)
[ 95/161] Fetching: reformasi-gereja-lahirnya-agama-protestan-di-dunia  (sejarah-sma-kelas-11)
[ 96/161] Fetching: renaissance-eropa-menuju-masa-kebangkitan  (sejarah-sma-kelas-11)
[ 97/161] Fetching: seri-revolusi-dunia-revolusi-tiongkok  (sejarah-sma-kelas-11)
[ 98/161] Fetching: revolusi-perancis  (sejarah-sma-kelas-11)
[ 99/161] Fetching: perang-aceh  (sejarah-sma-kelas-11)
[100/161] Fetching: perang-diponegoro  (sejarah-sma-kelas-11)
[101/161] Fetching: sejarah-kelas-11-mengenal-tokoh-tokoh-nasional-dalam-proklamasi-kemerdekaan-indonesia  (sejarah-sma-kelas-11)
[102/161] Fetching: perang-pattimura  (sejarah-sma-kelas-11)
[103/161] Fetching: perang-padri  (sejarah-sma-kelas-11)
[104/161] Fetching: kerajaan-maritim-hindu-buddha-di-nusantara  (sejarah-sma-kelas-11)
[105/161] Fetching: sejarah-kelas-11-liberalisme-dan-sosialisme-di-indonesia  (sejarah-sma-kelas-11)
[106/161] Fetching: sejarah-kelas-11-sejarah-besar-dunia-revolusi-industri  (sejarah-sma-kelas-11)
[107/161] Fetching: bentuk-perlawanan-rakyat-indonesia-terhadap-jepang  (sejarah-sma-kelas-11)
[108/161] Fetching: kehidupan-bangsa-indonesia-masa-pendudukan-jepang  (sejarah-sma-kelas-11)
[109/161] Fetching: aufklarung-masa-pencerahan-di-eropa  (sejarah-sma-kelas-11)
[110/161] Fetching: nasionalisme  (sejarah-sma-kelas-11)
[111/161] Fetching: sejarah-kelas-11-proses-terjadinya-revolusi-indonesia  (sejarah-sma-kelas-11)
[112/161] Fetching: dinamika-pemerintahan-pertama-ri  (sejarah-sma-kelas-11)
[113/161] Fetching: program-kerja-kabinet-djuanda  (sejarah-sma-kelas-12)
[114/161] Fetching: perkembangan-teknologi-informasi-dan-komunikasi-di-indonesia  (sejarah-sma-kelas-12)
[115/161] Fetching: sejarah-kelas-12-perkembangan-teknologi-arsitektur-dan-konstruksi-di-indonesia  (sejarah-sma-kelas-12)
[116/161] Fetching: sejarah-kelas-12-latar-belakang-lahirnya-revolusi-edsa-gerakan-people-power-filipina  (sejarah-sma-kelas-12)
[117/161] Fetching: berpisahnya-negara-negara-yugoslavia  (sejarah-sma-kelas-12)
[118/161] Fetching: perang-korea  (sejarah-sma-kelas-12)
[119/161] Fetching: sejarah-kelas-12-kronologi-terjadinya-perang-afghanistan-dan-uni-sovieti  (sejarah-sma-kelas-12)
[120/161] Fetching: perang-indocina-3-konflik-kamboja  (sejarah-sma-kelas-12)
[121/161] Fetching: peran-bangsa-indonesia-dalam-perdamaian-dunia  (sejarah-sma-kelas-12)
[122/161] Fetching: runtuhnya-tembok-berlin-dan-reunifikasi-jerman  (sejarah-sma-kelas-12)
[123/161] Fetching: runtuhnya-uni-soviet  (sejarah-sma-kelas-12)
[124/161] Fetching: konflik-palestina-israel  (sejarah-sma-kelas-12)
[125/161] Fetching: peristiwa-kontemporer-dunia-perpecahan-cekoslovakia  (sejarah-sma-kelas-12)
[126/161] Fetching: sejarah-kelas-12-5-perusahaan-ini-menjadi-bukti-perkembangan-teknologi-transportasi-indonesia  (sejarah-sma-kelas-12)
[127/161] Fetching: teknologi-luar-angkasa  (sejarah-sma-kelas-12)
[128/161] Fetching: perjalanan-politik-apartheid-di-afrika-selatan  (sejarah-sma-kelas-12)
[129/161] Fetching: mengetahui-sejarah-perkembangan-iptek-di-masa-kini  (sejarah-sma-kelas-12)
[130/161] Fetching: sejarah-perkembangan-transportasi  (sejarah-sma-kelas-12)
[131/161] Fetching: organisasi-ekonomi-regional-dan-global  (sejarah-sma-kelas-12)
[132/161] Fetching: organisasi-militer-internasional  (sejarah-sma-kelas-12)
[133/161] Fetching: sejarah-pemilu-1955  (sejarah-sma-kelas-12)
[134/161] Fetching: sejarah-kelas-12-sejarah-terjadinya-revolusi-hijau  (sejarah-sma-kelas-12)
[135/161] Fetching: kehidupan-politik-dan-ekonomi-masa-orde-baru  (sejarah-sma-kelas-12)
[136/161] Fetching: sejarah-kelas-12-revolusi-kuba-tetangga-yang-menjadi-ancaman-amerika-serikat  (sejarah-sma-kelas-12)
[137/161] Fetching: sejarah-kelas-12-negara-negara-pendukung-kemerdekaan-indonesia  (sejarah-sma-kelas-12)
[138/161] Fetching: sejarah-perang-dingin  (sejarah-sma-kelas-12)
[139/161] Fetching: sejarah-kelas-12-kehidupan-indonesia-di-masa-demokrasi-terpimpin  (sejarah-sma-kelas-12)
[140/161] Fetching: kehidupan-ekonomi-bangsa-indonesia-di-masa-demokrasi-liberal  (sejarah-sma-kelas-12)
[141/161] Fetching: sistem-demokrasi-liberal-di-indonesia  (sejarah-sma-kelas-12)
[142/161] Fetching: sejarah-kelas-12-sejarah-runtuhnya-vietnam-selatan-dan-bersatunya-menyatunya-vietnam  (sejarah-sma-kelas-12)
[143/161] Fetching: sejarah-kelas-12-kehidupan-ekonomi-dan-politik-masa-reformasi  (sejarah-sma-kelas-12)
[144/161] Fetching: pengakuan-india-atas-kemerdekaan-indonesia  (sejarah-sma-kelas-12)
[145/161] Fetching: mengetahui-hasil-konferensi-meja-bundar  (sejarah-sma-kelas-12)
[146/161] Fetching: konflik-timur-tengah-perang-irak-dan-iran  (sejarah-sma-kelas-12)
[147/161] Fetching: sejarah-pemberontakan-republik-maluku-selatan  (sejarah-sma-kelas-12)
[148/161] Fetching: peran-indonesia-dalam-menjaga-perdamaian-di-asia  (sejarah-sma-kelas-12)
[149/161] Fetching: tokoh-tokoh-yang-berjuang-mempertahankan-kemerdekaan-nkri  (sejarah-sma-kelas-12)
[150/161] Fetching: konflik-eritrea-ethiopia  (sejarah-sma-kelas-12)
[151/161] Fetching: program-kerja-dan-kemunduran-kabinet-ali-sastroamidjojo-2  (sejarah-sma-kelas-12)
[152/161] Fetching: latar-belakang-pemberontakan-andi-azis  (sejarah-sma-kelas-12)
[153/161] Fetching: sejarah-kelas-11-akar-dan-proses-proses-penerapan-demokrasi-indonesia  (sejarah-sma-kelas-12)
[154/161] Fetching: sejarah-kelas-12-peran-pemuda-di-masa-perubahan-orde-baru-dan-reformasi  (sejarah-sma-kelas-12)
[155/161] Fetching: sejarah-kelas-12-apa-itu-kerjasama-kawasan-utara-dan-kawasan-selatan  (sejarah-sma-kelas-12)
[156/161] Fetching: mengenal-sistem-ekonomi-ali-baba  (sejarah-sma-kelas-12)
[157/161] Fetching: latar-belakang-dan-tujuan-pemberontakan-prri-permesta  (sejarah-sma-kelas-12)
[158/161] Fetching: sejarah-kebijakan-gunting-syafruddin  (sejarah-sma-kelas-12)
[159/161] Fetching: proses-terbentuknya-kabinet-djuanda  (sejarah-sma-kelas-12)
[160/161] Fetching: program-kerja-kabinet-ali-sastroamidjojo-1  (sejarah-sma-kelas-12)
[161/161] Fetching: pemilu-pertama-di-kabinet-burhanuddin-harahap  (sejarah-sma-kelas-12)

 Successfully fetched: 161 / 161 articles

In [ ]:
lengths = [(r["title"], len(r["content_clean"])) for r in enriched_records]
lengths.sort(key=lambda x: x[1])

print("\n  Shortest articles (check for truncation):")
for title, length in lengths[:5]:
    print(f"  {length:>6} chars — {title}")

print("\n Longest articles:")
for title, length in lengths[-5:]:
    print(f"  {length:>6} chars — {title}")

  Shortest articles (check for truncation):
    2372 chars — Pemilu Pertama di Kabinet Burhanuddin Harahap | Sejarah Kelas 12
    2549 chars — Program Kerja dan Kemunduran Kabinet Ali Sastroamidjojo 2 | Sejarah Kelas 12
    2903 chars — Mengenal Sistem Ekonomi Ali Baba | Sejarah Kelas 12
    2911 chars — Perundingan Hooge-Veluwe: Upaya Indonesia Pertahankan Kemerdekaan
    3101 chars — Kebijakan Gunting Syafruddin | Sejarah Kelas 12

 Longest articles:
   18388 chars — Mengetahui Perkembangan IPTEK di Masa Kini | Sejarah Kelas 12
   19113 chars — 7 Peran Indonesia dalam Perdamaian Dunia | Sejarah Kelas 12
   20011 chars — 10 Organisasi Pergerakan Nasional Indonesia &#038; Tokoh Pendirinya | Sejarah Kelas 11
   21042 chars — Peradaban Yunani Kuno: Sejarah, Raja, dan Peninggalannya | Sejarah Kelas 10
   22434 chars — 13 Kerajaan Maritim Hindu-Buddha di Nusantara | Sejarah Kelas 11

In [ ]:
df = pd.DataFrame(enriched_records)

col_order = [
    "id", "title", "url", "slug", "date",
    "source_category", "excerpt_clean", "content_clean",
    "content", "excerpt",
]
df = df[[c for c in col_order if c in df.columns]]

print(f"Shape: {df.shape}")
print("\nSample:")
df[["title", "url", "source_category", "date",
    "source_category", "excerpt_clean", "content_clean",
    "content", "excerpt"]].head(10)

Shape: (161, 10)

Sample:

,title,url,source_category,date,source_category,excerpt_clean,content_clean,content,excerpt
0,"Kesultanan Samudera Pasai: Sejarah, Kejayaan, ...",https://www.ruangguru.com/blog/kerajaan-samude...,sejarah-smp-kelas-7,2025-05-16T10:00:00,sejarah-smp-kelas-7,Artikel Sejarah kelas 7 ini membahas tentang s...,Artikel Sejarah kelas 7 ini membahas tentang s...,"<p><img decoding=""async"" class=""aligncenter si...",<p>Artikel Sejarah kelas 7 ini membahas tentan...
1,Mengenal Sejarah Nenek Moyang Bangsa Indonesia...,https://www.ruangguru.com/blog/sejarah-nenek-m...,sejarah-smp-kelas-7,2024-09-25T04:00:00,sejarah-smp-kelas-7,"Yuk, kita bahas lebih jauh tentang sejarah asa...","Yuk, kita bahas lebih jauh tentang sejarah asa...","<p style=""text-align: justify;""><img decoding=...","<p>Yuk, kita bahas lebih jauh tentang sejarah ..."
2,Apakah Manusia Pernah Hidup Bersama Dinosaurus...,https://www.ruangguru.com/blog/manusia-dan-din...,sejarah-smp-kelas-7,2022-02-11T09:47:23,sejarah-smp-kelas-7,Apakah manusia pernah hidup bersama dinosaurus...,Apakah manusia pernah hidup bersama dinosaurus...,"<p><img decoding=""async"" style=""width: 820px; ...",<p>Apakah manusia pernah hidup bersama dinosau...
3,"Selain Avengers, Kerajaan Kediri juga Pernah M...",https://www.ruangguru.com/blog/perang-saudara-...,sejarah-smp-kelas-7,2019-10-18T12:00:00,sejarah-smp-kelas-7,Artikel ini menceritakan tentang perang saudar...,Artikel ini menceritakan tentang perang saudar...,"<p style=""text-align: center;""><img decoding=""...",<p>Artikel ini menceritakan tentang perang sau...
4,Kehidupan Masyarakat pada Masa Penjajahan Kolo...,https://www.ruangguru.com/blog/masa-penjajahan,sejarah-smp-kelas-8,2026-01-20T13:00:08,sejarah-smp-kelas-8,Artikel Sejarah kelas 8 ini menjelaskan tentan...,Artikel Sejarah kelas 8 ini menjelaskan tentan...,"<p><img decoding=""async"" class=""aligncenter si...",<p>Artikel Sejarah kelas 8 ini menjelaskan ten...
5,Tugas dan Tujuan Kedatangan NICA di Indonesia ...,https://www.ruangguru.com/blog/kedatangan-nica...,sejarah-smp-kelas-8,2024-05-28T10:00:00,sejarah-smp-kelas-8,Artikel Sejarah kelas 8 ini menjelaskan tentan...,Artikel Sejarah kelas 8 ini menjelaskan tentan...,"<p style=""text-align: center;""><img decoding=""...",<p>Artikel Sejarah kelas 8 ini menjelaskan ten...
6,"Sejarah, Tokoh, dan Tugas Pasukan AFNEI di Ind...",https://www.ruangguru.com/blog/kedatangan-pasu...,sejarah-smp-kelas-8,2024-04-23T13:00:00,sejarah-smp-kelas-8,Tahukah kamu tentang sejarah datangnya pasukan...,Tahukah kamu tentang sejarah datangnya pasukan...,"<p style=""text-align: center;""><img decoding=""...",<p>Tahukah kamu tentang sejarah datangnya pasu...
7,"Yuk, Kenali 6 Organisasi Pergerakan Indonesia ...",https://www.ruangguru.com/blog/tahukah-kamu-me...,sejarah-smp-kelas-8,2021-03-01T02:00:00,sejarah-smp-kelas-8,Tahukah kamu mengenai organisasi pergerakan In...,Tahukah kamu mengenai organisasi pergerakan In...,"<p><img decoding=""async"" src=""https://cdn-web....",<p>Tahukah kamu mengenai organisasi pergerakan...
8,Latar Belakang Masa Orde Baru &#038; Sistem Pe...,https://www.ruangguru.com/blog/sejarah-kelahir...,sejarah-smp-kelas-9,2026-01-05T14:00:00,sejarah-smp-kelas-9,Artikel Sejarah kelas 9 ini akan membahas tent...,Artikel Sejarah kelas 9 ini akan membahas tent...,"<p style=""text-align: justify;""><img decoding=...",<p>Artikel Sejarah kelas 9 ini akan membahas t...
9,"Perjanjian Renville: Latar Belakang, Hasil &#0...",https://www.ruangguru.com/blog/mengenal-perjan...,sejarah-smp-kelas-9,2025-11-17T02:45:31,sejarah-smp-kelas-9,"Setelah merdeka, ternyata Indonesia masih haru...","Setelah merdeka, ternyata Indonesia masih haru...","<p><img decoding=""async"" class=""aligncenter si...","<p>Setelah merdeka, ternyata Indonesia masih h..."

In [ ]:
OUTPUT_FILE = "ruangguru_sejarah_kelas7_12.csv"

df_clean = df.drop(columns=["content", "excerpt"], errors="ignore")

df_clean.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig",
    quoting=csv.QUOTE_ALL,
)

print(f" Saved {len(df_clean)} rows -> {OUTPUT_FILE}")

 Saved 161 rows → ruangguru_sejarah_kelas7_12.csv

In [ ]:
print("Articles per source_category:")
print(df["source_category"].value_counts().to_string())

print("\nDate range:")
print(f"  Oldest : {df['date'].min()}")
print(f"  Newest : {df['date'].max()}")

print("\nAvg content length (chars):")
print(f"  {df['content_clean'].str.len().mean():.0f} chars/article")

sample = df.iloc[0]
print(f"\n── Sample Article ──────────────────────────────────")
print(f"Title   : {sample['title']}")
print(f"URL     : {sample['url']}")
print(f"Category: {sample['source_category']}")
print(f"Date    : {sample['date']}")
print(f"Chars   : {len(sample['content_clean'])}")
print(f"\nFull Content:\n{sample['content_clean']}")

Articles per source_category:
source_category
sejarah-sma-kelas-11    49
sejarah-sma-kelas-12    49
sejarah-sma-kelas-10    42
sejarah-smp-kelas-9     13
sejarah-smp-kelas-8      4
sejarah-smp-kelas-7      4

Date range:
  Oldest : 2017-09-22T06:03:08
  Newest : 2026-05-19T09:35:44

Avg content length (chars):
  9032 chars/article

── Sample Article ──────────────────────────────────
Title   : Kesultanan Samudera Pasai: Sejarah, Kejayaan, dan Keruntuhan | Sejarah Kelas 7
URL     : https://www.ruangguru.com/blog/kerajaan-samudera-pasai
Category: sejarah-smp-kelas-7
Date    : 2025-05-16T10:00:00
Chars   : 5019

Full Content:
Artikel Sejarah kelas 7 ini membahas tentang sejarah, masa kejayaan, dan penyebab runtuhnya Kesultanan Samudera Pasai. —   Selain Kerajaan Hindu-Budha, ternyata Nusantara juga punya Kerajaan atau Kesultanan Islam, loh. Munculnya Kesultanan Islam di Indonesia disebabkan oleh para pedagang Islam dari Arab, India, dan Persia yang awalnya singgah untuk berdagang, lama kelamaan menetap dan membangun kerajaan. Sebenarnya, ada banyak Kesultanan Islam di Indonesia, salah satu yang terkenal adalah Kesultanan Samudera Pasai. Kesultanan Samudera Pasai diperkirakan berdiri pada pertengahan abad ke-13 Masehi. Kerajaan Samudra Pasai didirikan oleh Malikussaleh atau Malik al-Saleh. Kerajaan ini terletak di Kecamatan Samudera, Kabupaten Aceh Utara. Wilayah tersebut diapit oleh dua sungai besar yaitu Sungai Peusangan dan Sungai Pasai. Sumber sejarah dari Kerajaan Samudera Pasai antara lain Hikayat Raja-Raja Pasai, Kitab Sejarah Melayu, Tuhfat Al Nazha yang ditulis oleh Ibnu Batutah, hingga prasasti yang berbahasa Arab dan Melayu Kuno.   Silsilah Kepemimpinan Kesultanan Samudera Pasai Kesultanan Samudera Pasai dipimpin oleh raja atau sultan yang juga memberikan pengaruhnya terhadap kerajaan dan masyarakat sekitar. Berikut ini, telah dirangkum nama-nama raja yang pernah memimpin Kerajaan Samudera Pasai beserta masa kepemimpinannya. Yuk, lihat gambar di bawah.   Nah, di antara raja-raja yang disebutkan di atas, ada beberapa raja yang perannya cukup besar hingga membuat Kerajaan Samudera Pasai mengalami masa kejayaan. Yuk, simak penjelasan di bawah!   1. Sultan Malik Al-Saleh (1267-1297) Pada tahun 1267, Kerajaan Samudera Pasai dipimpin oleh Meurah Silu dengan gelar Sultan Malik Al-Saleh. Di masa pemerintahannya, Kerajaan Samudera Pasai berhasil menguasai Selat Malaka yang pada saat itu menjadi pusat perdagangan internasional dengan lada sebagai salah satu komoditas ekspor utamanya. Selain lada, Kerajaan Samudera Pasai juga mengekspor sutra dan kapur barus. Kerajaan Samudra Pasai menjadi pusat perdagangan karena letaknya yang strategis sehingga banyak disinggahi oleh berbagai orang dari mancanegara. Selain itu, komoditas yang dihasilkan sebagai lada sangat dibutuhkan oleh masyarakat dunia. Baca Juga: Jalur Rempah Nusantara: Pengertian, Sejarah, dan Pengaruhnya   2. Sultan Muhammad Az-Zahir (1297-1326) Setelah Sultan Malik Al-Saleh wafat pada tahun 1297, kepemimpinan Kerajaan Samudera Pasai dilanjutkan oleh anaknya, yaitu Sultan Muhammad Malik Az-Zahir. Sang raja baru ini untuk pertama kalinya memperkenalkan koin emas atau dirham sebagai mata uang.   Mata uang dirham secara resmi digunakan dalam perdagangan di Kerajaan Samudera Pasai pada tahun 1297. Mata uang ini berupa kepingan emas yang memiliki diameter 10 mm dan berat sekitar 0,6 gram. Sisi atas bertuliskan Muhammad Malik Al-Zahir dan sisi bawah bertuliskan Al-Sultan al-adil yang artinya sultan harus memberi keadilan terhadap masyarakat.   3. Sultan Mahmud Malik Az-Zahir (1326-1345) Pada tahun 1326, tahta kerajaan diteruskan oleh Sultan Mahmud Malik Az-Zahir. Di masa pemerintahannya, Kerajaan Samudera Pasai terkenal sebagai kerajaan dagang yang maju. Di tempat ini, banyak dijumpai pedagang dari India dan Cina yang membeli rempah-rempah, terutama lada. Selain itu, di Kerajaan Samudera Pasai terdapat beberapa jenis barang dari Cina yang dapat dibeli pedagang tanpa harus berlayar ke Cina. Berikut ini telah dirangkum beberapa aspek yang mendukung kemajuan Kerajaan Samudera Pasai. Mau tau apa aja? Yuk, simak gambar berikut.   Runtuhnya Kesultanan Samudera Pasai Tidak selamanya kerajaan mengalami kejayaan, pasti ada masanya ia akan runtuh. Sama halnya seperti Kerajaan Samudera Pasai. Pada tahun 1521 di bawah pimpinan Sultan Zain Al-Abidin, Portugis menyerang kerajaan ini karena iri dengan kemajuan dagang mereka yang begitu pesat. Angkatan perang Portugis yang lebih kuat, akhirnya mereka berhasil menaklukkan Kerajaan Samudera Pasai. Keadaan kerajaan yang melemah ini, kemudian dimanfaatkan oleh Sultan Ali Mughayat Syah, raja Kerajaan Aceh Darussalam untuk mengambil alih Kerajaan Samudera Pasai. Pada tahun 1524, akhirnya Kerajaan Samudra Pasai dimasukkan ke dalam wilayah Kerajaan Aceh Darussalam. Hal tersebut dibuktikan dengan dipindahkan Lonceng Cakra Donya milik Kerajaan Samudera Pasai ke Kerajaan Aceh Darussalam. Nah, Lonceng Cakra Donya ini juga merupakan peninggalan dari Kesultanan Samudera Pasai, ya! — Nah, itu tadi beberapa penjelasan tentang sejarah hingga runtuhnya Kerajaan Samudera Pasai. Menarik bukan? Masih banyak loh materi Sejarah lainnya yang bisa kamu dapatkan. Yuk, cek ruangbelajar dan temukan video animasi yang akan mendukung kegiatan belajar kamu. Referensi:  Gunawan, Restu. (2017) Sejarah Indonesia Kelas X. Jakarta: Kemendikbud RI. Sumber Foto: Foto Lonceng Cakra Donya . Tautan: https://acehtourism.travel/situs-sejarah-tsunami/03/2019/lonceng-cakra-donya-kisah-persahabatan-cheng-ho-dengan-kerajaan-aceh/ (Diakses: 13 November 2020)   Artikel ini terakhir diperbarui pada 16 Mei 2025.